Repository libjxl/libjxl, pull requests merged in 2021-06, with the labels that each got.

#54 Fuzz: Undefined-shift in jxl::ModularFrameDecoder::FinalizeDecoding
  lib/jxl/modular/transform/palette.h
Labels: fuzzerbug

#59 split off the benchmarking section to a separate doc
  README.md
  doc/benchmarking.md
Labels: documentation

#74 set modular_16_bit_buffer_sufficient header field
  lib/jxl/image_metadata.cc
  lib/jxl/image_metadata.h
Labels: bug, encoder

#68 Run YCbCr channel upsampling per-group.
  lib/jxl/dec_cache.h
  lib/jxl/dec_group.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/dec_xyb.cc
  lib/jxl/dec_xyb.h
Labels: decoder, enhancement

#84 Make kBradford and kBradfordInv const.
  lib/jxl/color_encoding_internal.cc
Labels: cleanup

#73 Progressive steps
  lib/jxl/enc_file.cc
  tools/cjxl.cc
Labels: cjxl

#80 Fix a couple of strings in encoder
  AUTHORS
  tools/args.h
  tools/cjxl.cc
Labels: cjxl

#79 don't do lossy palette when also doing lossy
  lib/jxl/enc_modular.cc
Labels: bug, cjxl

#60 Fuzz: Integer-overflow in jxl::palette_internal::GetPaletteValue
  lib/jxl/modular/transform/palette.h
Labels: fuzzerbug

#88 Add ccache to the pipeline to speed it up
  .github/workflows/build_test.yml
Labels: enhancement, meta repo, speedup

#95 fix check in MaybeSetFloatCallback, factor out duplicate code
  lib/jxl/dec_frame.h
Labels: bug, cleanup, decoder

#93 Refactor decoding Jxl to JPEG out of decode.cc
  lib/jxl.cmake
  lib/jxl/decode.cc
  lib/jxl/decode_to_jpeg.cc
  lib/jxl/decode_to_jpeg.h
  lib/lib.gni
Labels: cleanup

#83 do unpremultiply if needed in ConvertToExternal
  lib/jxl/dec_external_image.cc
  lib/jxl/dec_frame.h
Labels: bug, decoder

#39 Install JDK into docker image (for testing JNI wrapper).
  .gitlab-ci.yml
  docker/scripts/emsdk_install.sh
  docker/scripts/jpegxl_builder.sh
Labels: building/portability

#97 New JPEGXL_ENABLE_TRANSCODE_JPEG build flag to disable decoding to JPEG
  .github/workflows/build_test.yml
  CMakeLists.txt
  lib/jxl.cmake
  lib/jxl/common.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/decode_to_jpeg.cc
  lib/jxl/decode_to_jpeg.h
  lib/jxl/encode_test.cc
  lib/jxl/image_bundle.h
  lib/jxl/jpeg/jpeg_data.cc
  lib/jxl/jpeg/jpeg_data.h
  lib/jxl/jxl_test.cc
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_utils.h
Labels: api, building/portability, decoder

#117 Use up all bytes of box to skip
  lib/jxl/decode.cc
Labels: api, decoder, speedup

#11 Fuzz: accessing undefined values
  lib/jxl/dec_modular.cc
  lib/jxl/enc_modular.cc
  lib/jxl/modular/encoding/encoding.cc
  lib/jxl/modular/encoding/encoding.h
  lib/jxl/modular/options.h
Labels: fuzzerbug

#120 Remove overzealous chromaticity check
  lib/jxl/color_encoding_internal.cc
Labels: bug, encoder

#121 mark DC API functions as deprecated
  lib/include/jxl/decode.h
  lib/jxl_tests.cmake
  tools/CMakeLists.txt
Labels: api, documentation

#82 Add --premultiply option to cjxl
  lib/jxl/codec_in_out.h
  lib/jxl/image_bundle.cc
  lib/jxl/image_bundle.h
  lib/jxl/jxl_test.cc
  tools/cjxl.cc
  tools/cjxl.h
Labels: cjxl

#124 Remove DC implementation
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl_tests.cmake
  tools/CMakeLists.txt
  tools/djxl_fuzzer.cc
Labels: api, cleanup

#127 Silence deprecation warnings when building with gcc
  lib/jxl.cmake
  lib/jxl_tests.cmake
  tools/CMakeLists.txt
Labels: building/portability

#132 Non-optimized SkipFrames implementation
  lib/include/jxl/decode.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: api, decoder

#123 add cjxl option --keep_invisible
  lib/jxl/enc_cache.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_params.h
  tools/cjxl.cc
  tools/cjxl.h
Labels: cjxl, encoder, enhancement

#131 Fuzz: do proper division for negative values.
  lib/jxl/dec_reconstruct.cc
Labels: fuzzerbug

#135 Don't decode frame if skipped and not referenced
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: api, decoder, speedup

#133 Run CIFuzz continuous integration on PRs.
  .github/workflows/fuzz.yml
Labels: fuzzerbug, meta repo

#146 Remove extra comma in lib/lib.gni
  lib/lib.gni
Labels: building/portability, cleanup

#139 Refactor the group border handling logic.
  lib/jxl.cmake
  lib/jxl/dec_cache.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.cc
  lib/jxl/dec_group.cc
  lib/jxl/dec_group_border.h
  lib/jxl/dec_reconstruct.cc
  lib/lib.gni
Labels: cleanup

#145 check earlier and better if RCT operates on valid channels
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/subtractgreen.h
  lib/jxl/modular/transform/transform.cc
  lib/jxl/modular/transform/transform.h
Labels: cleanup, fuzzerbug

#142 don't use ClampToRange in modular
  lib/jxl/common.h
  lib/jxl/modular/encoding/context_predict.h
  lib/jxl/modular/transform/squeeze.h
  lib/jxl/modular/transform/subtractgreen.h
Labels: cleanup, speedup

#148 fuzzer_corpus: Add parameter to run quiet.
  tools/fuzzer_corpus.cc
Labels: building/portability, fuzzerbug, meta repo

#143 Let skip frames add to existing amount
  lib/include/jxl/decode.h
  lib/jxl/decode.cc
Labels: api

#152 modular cleanup
  ci.sh
  lib/jxl.cmake
  lib/jxl/enc_modular.cc
  lib/jxl/enc_params.h
  lib/jxl/jxl_test.cc
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/modular_image.h
  lib/jxl/modular/transform/near-lossless.h
  lib/jxl/modular/transform/squeeze.h
  lib/jxl/modular/transform/transform.cc
  lib/jxl/modular/transform/transform.h
  lib/lib.gni
  tools/benchmark/benchmark_codec_jxl.cc
  tools/cjxl.cc
Labels: cleanup

#151 Fix for https://github.com/libjxl/libjxl/issues/150
  lib/jxl/enc_file.cc
  lib/jxl/enc_frame.cc
Labels: bug

#134 Verify the size of reference frames when saving them
  lib/jxl/blending.cc
  lib/jxl/dec_frame.cc
  lib/jxl/frame_header.cc
Labels: fuzzerbug

#154 Add F16 support to JNI wrapper.
  tools/CMakeLists.txt
  tools/jni/org/jpeg/jpegxl/wrapper/Decoder.java
  tools/jni/org/jpeg/jpegxl/wrapper/DecoderJni.java
  tools/jni/org/jpeg/jpegxl/wrapper/DecoderTest.java
  tools/jni/org/jpeg/jpegxl/wrapper/ImageData.java
  tools/jni/org/jpeg/jpegxl/wrapper/PixelFormat.java
  tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.cc
  tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.h
Labels: building/portability

#14 Improve djxl_fuzzer
  tools/djxl_fuzzer.cc
  tools/fuzzer_corpus.cc
Labels: enhancement, fuzzerbug

#155 some more modular cleanup
  lib/jxl.cmake
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/rct.h
  lib/jxl/modular/transform/transform.cc
  lib/jxl/modular/transform/transform.h
  lib/lib.gni
Labels: cleanup

#160 replace modular image minval maxval with bitdepth
  lib/jxl/dec_modular.cc
  lib/jxl/enc_modular.cc
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/modular_image.cc
  lib/jxl/modular/modular_image.h
  lib/jxl/modular/transform/palette.h
Labels: cleanup

#161 fix *san complaining about 1 << 32
  lib/jxl/enc_modular.cc
Labels: cleanup

#114 Avoid extra computation for empty histograms in clustering.
  lib/jxl/enc_cluster.cc
Labels: encoder, speedup

#163 avoid << 32 also in decoder
  lib/jxl/dec_modular.cc
Labels: cleanup

#10 Limit tree size for DC tiles
  lib/jxl/modular/encoding/encoding.cc
Labels: fuzzerbug

#162 pull modular fwd transforms out of libjxl_dec
  lib/jxl.cmake
  lib/jxl/enc_modular.cc
  lib/jxl/modular/modular_image.cc
  lib/jxl/modular/modular_image.h
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/enc_palette.h
  lib/jxl/modular/transform/enc_rct.cc
  lib/jxl/modular/transform/enc_rct.h
  lib/jxl/modular/transform/enc_squeeze.cc
  lib/jxl/modular/transform/enc_squeeze.h
  lib/jxl/modular/transform/enc_transform.cc
  lib/jxl/modular/transform/enc_transform.h
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/rct.h
  lib/jxl/modular/transform/squeeze.cc
  lib/jxl/modular/transform/squeeze.h
  lib/jxl/modular/transform/transform.cc
  lib/jxl/modular/transform/transform.h
  lib/lib.gni
Labels: cleanup

#166 when using container, also show total size
  tools/cjxl_main.cc
Labels: cjxl

#173 Fuzz: do not (re)move color planes before spot-colors are rendered
  lib/jxl/dec_frame.cc
Labels: fuzzerbug

#174 compute_minmax is encode-only, real_nb_channels is not needed
  lib/jxl/dec_modular.cc
  lib/jxl/enc_modular.cc
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/encoding/encoding.cc
  lib/jxl/modular/modular_image.cc
  lib/jxl/modular/modular_image.h
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/enc_transform.cc
  lib/jxl/modular/transform/enc_transform.h
Labels: cleanup

#175 simplify modular channel resize()
  lib/jxl/dec_modular.cc
  lib/jxl/enc_modular.cc
  lib/jxl/modular/encoding/encoding.cc
  lib/jxl/modular/modular_image.h
  lib/jxl/modular/transform/squeeze.cc
Labels: cleanup, speedup

#176 Add "ci.sh ossfuzz_*" commands to help repro oss-fuzz bugs
  ci.sh
  tools/ossfuzz-build.sh
Labels: building/portability, fuzzerbug

#181 Upsampling: fix overwrite at right border
  lib/jxl/dec_upsample.cc
Labels: bug, regression

#182 Simplifying speed heuristics
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_heuristics.cc
Labels: encoder quality

#194 fix default squeeze params
  lib/jxl/modular/transform/squeeze.cc
Labels: bug, decoder

#190 remove another unnecessary modular image field
  lib/jxl/dec_modular.cc
  lib/jxl/enc_modular.cc
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/encoding/encoding.cc
  lib/jxl/modular/modular_image.cc
  lib/jxl/modular/modular_image.h
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/squeeze.cc
Labels: cleanup

#195 improve squeeze param check
  lib/jxl/modular/transform/enc_squeeze.cc
  lib/jxl/modular/transform/squeeze.cc
  lib/jxl/modular/transform/squeeze.h
Labels: bug, decoder

#199 Store frame dependency graph on rewind
  lib/jxl/dec_frame.cc
  lib/jxl/dec_frame.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: api, decoder, speedup

#198 push global RCT to groups if possible, parallelize otherwise
  lib/jxl/dec_modular.cc
  lib/jxl/dec_modular.h
  lib/jxl/modular/transform/rct.h
  lib/jxl/modular/transform/transform.cc
Labels: speedup

#206 Support low memory if exif orientation is kept
  lib/include/jxl/decode.h
  lib/jxl/dec_frame.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: api, decoder, speedup

#172 Reversing the decision tree
  lib/jxl/decode_test.cc
  lib/jxl/enc_ac_strategy.cc
Labels: encoder, encoder quality, enhancement

#212 Pull sanitizer-specific code to sanitizers.h
  lib/extras/codec_gif.cc
  lib/extras/codec_jpg.cc
  lib/jxl.cmake
  lib/jxl/common.h
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/filters.h
  lib/jxl/image.cc
  lib/jxl/sanitizers.h
  lib/lib.gni
  tools/benchmark/benchmark_codec_jpeg.cc
  tools/benchmark/benchmark_codec_webp.cc
Labels: cleanup

#189 Fix: float-to-int-overflow
  lib/jxl/dec_external_image.cc
Labels: bug, fuzzerbug

#203 OssFuzz: Do not read/use undefined values in UndoXYB
  lib/jxl/dec_reconstruct.cc
Labels: fuzzerbug

#221 Try merging 16x8 and 8x16 fairly, not sequentially
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/jxl_test.cc
Labels: encoder quality

#222 Fuzz: validate rendering intent
  lib/extras/codec_png.cc
Labels: fuzzerbug

#223 minor ac block ctx tweak
  lib/jxl/enc_heuristics.cc
Labels: encoder, enhancement

#249 Clockwise order for centerfirst group order
  lib/jxl/enc_frame.cc
Labels: encoder, enhancement
