Repository libjxl/libjxl, pull requests merged in 2021-05, with the labels that each got.

#20 Improve fuzzing
  tools/djxl_fuzzer.cc
  tools/fuzzer_corpus.cc
Labels: enhancement, fuzzerbug

#30 Fuzz: fix heap-buffer-overflow in codec_psd
  lib/extras/codec_psd.cc
Labels: cjxl, fuzzerbug

#34 Use disabled-targets instead of build-only-scalar
  .gitlab-ci.yml
Labels: building/portability

#13 Allow alternative to linear srgb when xyb with ICC
  lib/include/jxl/decode.h
  lib/jxl/color_encoding_internal.cc
  lib/jxl/color_encoding_internal.h
  lib/jxl/dec_file.cc
  lib/jxl/dec_xyb.cc
  lib/jxl/dec_xyb.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_cache.cc
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
Labels: enhancement

#45 Update build command in README.md
  README.md
Labels: building/portability, documentation

#35 inverse palette bugfix: preserve hshift/vshift
  lib/jxl/modular/transform/palette.h
Labels: decoder bug, fuzzerbug

#9 SIMDify upsampling
  lib/jxl/dec_cache.h
  lib/jxl/dec_group.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/dec_upsample.cc
  lib/jxl/dec_upsample.h
Labels: speedup

#48 fix: unused CPU_[ZERO|SET] on HaikuOS
  AUTHORS
  tools/cpu/os_specific.cc
Labels: building/portability

#49 Fuzz: fix expectation
  tools/djxl_fuzzer.cc
Labels: fuzzerbug

#52 Update instructions to fetch a pull request
  doc/developing_in_github.md
Labels: documentation, meta repo

#46 Fuzz: fix read of undefined value
  lib/extras/codec_pnm.cc
Labels: cjxl, fuzzerbug

#50 make default encode from gif/jpg do the same as -d 0 / -q 100
  tools/cjxl.cc
Labels: cjxl

#51 New GitHub workflow to build and test several modes.
  .github/workflows/build_test.yml
  .github/workflows/pull_request.yml
  .gitlab-ci.yml
  bash_test.sh
Labels: building/portability, meta repo

#58 Fuzz: set_from_bytes timeout
  lib/extras/codec_jpg.cc
Labels: cjxl, fuzzerbug

#65 Fuzz: Don't support DC output if pixel callback
  lib/jxl/decode.cc
Labels: api, decoder, fuzzerbug
