Repository libjxl/libjxl, pull requests merged in 2021-12, with the labels that each got.

#926 Add a function to the C API to allow replacing the default CMS
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
Labels: encoder, api

#923 use libpng for all png decoding
  lib/extras/codec.cc
  lib/extras/codec_apng.cc
  lib/extras/codec_png.cc
  lib/extras/codec_png.h
  tools/benchmark/benchmark_codec.cc
  tools/benchmark/benchmark_codec_png.cc
  tools/cjxl.cc
Labels: cjxl, cleanup

#936 Do not ignore fatal error on group decoding.
  lib/jxl/dec_modular.cc
Labels: fuzzerbug, progressive

#845 encoder api: extra channels
  lib/include/jxl/encode.h
  lib/jxl/enc_external_image.cc
  lib/jxl/enc_external_image.h
  lib/jxl/encode.cc
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_utils.h
Labels: encoder, api

#941 Implement frame animation settings in encoder API
  CHANGELOG.md
  lib/include/jxl/encode.h
  lib/jxl/enc_frame.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/encode_test.cc
  lib/jxl/image_bundle.h
Labels: encoder, api

#957 allow thermal channels
  lib/jxl/image_metadata.h
  lib/jxl/roundtrip_test.cc
Labels: bug

#985 make djxl handle jxlp
  lib/jxl/jxl_test.cc
  tools/box/box.cc
  tools/box/box.h
  tools/box/box_test.cc
  tools/cjxl_main.cc
  tools/djxl.cc
  tools/djxl_main.cc
Labels: bug, djxl, container/metadata

#981 Improve encoder API blending support
  lib/jxl/enc_frame.cc
  lib/jxl/enc_frame.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
Labels: encoder, api

#988 Allow setting extra channel blend info in enc API
  CHANGELOG.md
  lib/include/jxl/encode.h
  lib/jxl/enc_frame.cc
  lib/jxl/enc_frame.h
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/encode_test.cc
Labels: encoder, api

#888 fix no-coalescing fuzzerbugs
  lib/jxl/dec_external_image.cc
  lib/jxl/decode.cc
Labels: fuzzerbug, testing

#613 allow virtual predictors 14 and 15 in cjxl -P
  lib/jxl/modular/options.h
  tools/args.h
Labels: cjxl

#1004 reduce MSVC warnings a bit
  lib/jxl/bit_reader_test.cc
  lib/jxl/convolve.cc
  lib/jxl/convolve_test.cc
  lib/jxl/data_parallel_test.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_external_image.cc
  lib/jxl/dec_frame.cc
  lib/jxl/dec_frame.h
  lib/jxl/dec_modular.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/dec_xyb.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_detect_dots.cc
  lib/jxl/enc_external_image.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/enc_image_bundle.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/enc_xyb.cc
  lib/jxl/gauss_blur.cc
  lib/jxl/lehmer_code_test.cc
  lib/jxl/modular/encoding/context_predict.h
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/rct.cc
  lib/jxl/modular/transform/squeeze.cc
  lib/jxl/noise.h
  lib/jxl/passes_test.cc
  lib/jxl/quantizer.h
  lib/jxl/splines.cc
  lib/jxl/xorshift128plus_test.cc
Labels: building/portability, cleanup

#1011 make tests faster
  lib/jxl/ans_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/xorshift128plus_test.cc
Labels: speedup, testing

#1014 fix MSYS test and speedup some more tests
  lib/jxl/ac_strategy_test.cc
  lib/jxl/coeff_order_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/lehmer_code_test.cc
Labels: speedup, testing

#870 Proposed documentation wording tweaks.
  lib/include/jxl/decode.h
Labels: documentation, decoder, api

#1016 ensure at least 2 mantissa bits
  lib/jxl/encode.cc
Labels: encoder, api

#1018 jxl_threads: Hide all the std namespace symbols.
  AUTHORS
  lib/jxl_threads.cmake
Labels: CI:full

#986 Use bionic image for cross-compilation.
  .github/workflows/build_test.yml
Labels: building/portability, CI:full

#1005 simplify data_parallel.h
  lib/extras/codec_exr.cc
  lib/extras/hlg.cc
  lib/extras/tone_mapping.cc
  lib/jxl/adaptive_reconstruction_test.cc
  lib/jxl/base/data_parallel.h
  lib/jxl/bit_reader_test.cc
  lib/jxl/compressed_dc.cc
  lib/jxl/convolve.cc
  lib/jxl/convolve_test.cc
  lib/jxl/dct_test.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_external_image.cc
  lib/jxl/dec_frame.cc
  lib/jxl/dec_frame.h
  lib/jxl/dec_modular.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/dec_xyb.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_cache.cc
  lib/jxl/enc_cache.h
  lib/jxl/enc_detect_dots.cc
  lib/jxl/enc_external_image.cc
  lib/jxl/enc_fast_heuristics.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/enc_image_bundle.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/enc_xyb.cc
  lib/jxl/enc_xyb.h
  lib/jxl/gauss_blur.cc
  lib/jxl/lehmer_code_test.cc
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/rct.cc
  lib/jxl/modular/transform/squeeze.cc
  lib/jxl/opsin_inverse_test.cc
  lib/jxl/passes_test.cc
  lib/jxl/xorshift128plus_test.cc
  lib/threads/thread_parallel_runner_test.cc
  tools/benchmark/benchmark_xl.cc
  tools/fuzzer_corpus.cc
  tools/hdr/display_to_hlg.cc
  tools/hdr/generate_lut_template.cc
  tools/hdr/pq_to_hlg.cc
  tools/hdr/render_hlg.cc
  tools/hdr/texture_to_cube.cc
  tools/hdr/tone_map.cc
Labels: building/portability, cleanup

#1025 fix png encode msan fail
  lib/extras/codec_apng.cc
Labels: bug, cjxl

#946 make modular encoding faster (mostly lightning)
  lib/jxl/enc_ans.cc
  lib/jxl/enc_ans.h
  lib/jxl/enc_modular.cc
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/transform/enc_rct.cc
  lib/jxl/modular/transform/enc_rct.h
  lib/jxl/modular/transform/enc_transform.cc
Labels: encoder, speedup

#1031 add -fno-rtti flag
  CMakeLists.txt
Labels: CI:full

#1006 add support for encoding cropped frames
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
Labels: encoder, api

#996 add no-coalescing to djxl_fuzzer
  tools/djxl_fuzzer.cc
Labels: testing

#1037 Use bundled png for WASM
  .github/workflows/build_test.yml
  CMakeLists.txt
  lib/jxl_extras.cmake
  third_party/CMakeLists.txt
  tools/CMakeLists.txt
Labels: CI:full

#1042 fix bugs in extra channel encoding
  lib/jxl/enc_external_image.cc
  lib/jxl/encode.cc
  lib/jxl/image_bundle.cc
Labels: bug, encoder, api

#606 decode_progressive: example application to demo/simulate/test progressive decoding
  examples/CMakeLists.txt
  examples/decode_progressive.cc
  examples/examples.cmake
Labels: progressive

#1060 Prohibit Palette with nonzero predictor when bits_per_sample > 24
  lib/jxl/modular/transform/transform.cc
Labels: spec
