Repository libjxl/libjxl, pull requests merged in 2021-10, with the labels that each got.

#663 drop ==, != from dec_params.h
  lib/jxl/dec_params.h
  tools/benchmark/benchmark_codec_jxl.cc
Labels: cleanup

#675 Fix progressive previews with chroma subsampling.
  lib/jxl/dec_group.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/dec_reconstruct.h
  lib/jxl/jxl_test.cc
Labels: merge-0.6

#676 Simplify box handling in decode.cc
  lib/include/jxl/decode.h
  lib/jxl/decode.cc
  lib/jxl/decode_to_jpeg.h
Labels: api, container/metadata

#678 Remove sys/platform/ppc.h include.
  tools/cpu/cpu.cc
Labels: building/portability, cleanup

#679 tweaks to lossless jpeg recompression
  lib/jxl/enc_cache.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_modular.h
Labels: encoder, speedup, density

#681 Fix skcms subdirectory build
  AUTHORS
  third_party/skcms.cmake
Labels: building/portability

#674 remove debug printing instrumentation on header fields
  lib/jxl/fields.cc
  lib/jxl/fields.h
Labels: cleanup

#690 Implement JXL_DEC_BOX event and getting box info
  lib/include/jxl/decode.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: api, container/metadata
