Repository libjxl/libjxl, pull requests merged in 2021-11, with the labels that each got.

#791 expose decode option to disable spot color rendering
  lib/include/jxl/decode.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: enhancement, decoder, api

#780 Use enum for encoder distance and effort options
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
  plugins/gimp/file-jxl-save.cc
Labels: encoder, api

#427 WIP: attempts at more precise JPEG encoder.
  tools/CMakeLists.txt
  tools/README.cjpeg_hdr.md
  tools/cjpeg_hdr.cc
  tools/cjxl.cc
Labels: enhancement

#792 make djxl_conformance return all extra channels
  tools/conformance/djxl_conformance.cc
Labels: decoder, testing

#811 Add JxlDecoderCloseInput to decoder API
  CHANGELOG.md
  examples/decode_exif_metadata.cc
  examples/decode_oneshot.cc
  lib/include/jxl/decode.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  tools/djxl_fuzzer.cc
Labels: decoder, api

#774 initialize cparams
  tools/jxl_from_tree.cc
Labels: bug

#816 Addes more missing options to the encoder API
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
Labels: encoder, api

#721 adjust MA tree size limits
  lib/jxl/dec_modular.cc
  lib/jxl/modular/encoding/encoding.cc
Labels: fuzzerbug

#819 Add progressive option to the encoder API
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
Labels: api

#359 allow redundant quant table in jbrd
  lib/jxl/dec_frame.cc
  lib/jxl/jpeg/jpeg_data.cc
Labels: enhancement, merge-0.6

#826 encoder api: function headers for extra channels
  lib/include/jxl/encode.h
Labels: encoder, api

#825 add test for upsampling and fix uint8 upsampling bug
  lib/jxl/dec_reconstruct.cc
  lib/jxl/decode_test.cc
Labels: bug, decoder, merge-0.6, testing

#821 Add palette options to encoder API
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
Labels: encoder, api

#846 JPG codec: use num_components instead of output_components...
  lib/extras/codec_jpg.cc
Labels: bug, djxl, fuzzerbug

#852 Add use-boxes and close-boxes functions to encoder API
  lib/include/jxl/encode.h
Labels: encoder, api

#862 call JxlDecoderCloseInput and fclose in jxlinfo
  examples/jxlinfo.c
Labels: documentation, decoder, api

#474 remove unnecessary patch clamping
  lib/jxl/enc_modular.cc
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/jxl_test.cc
Labels: encoder, cleanup, density, merge-0.6

#669 don't report coverage of debug-printing code
  ci.sh
  lib/jxl/aux_out.cc
  lib/jxl/aux_out.h
Labels: cleanup

#867 Implement JxlEncoderAddBox in the encoder API
  CHANGELOG.md
  lib/include/jxl/encode.h
  lib/jxl/decode.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/encode_test.cc
Labels: encoder, api

#857 fix MA tree size check
  lib/jxl/dec_modular.cc
  lib/jxl/modular/encoding/dec_ma.cc
Labels: bug, decoder

#856 make tests a bit faster
  lib/jxl/decode_test.cc
  lib/jxl/encode_test.cc
Labels: speedup, testing

#592 Make progressive decode work (better)
  lib/jxl/dec_frame.cc
  lib/jxl/dec_modular.cc
  lib/jxl/dec_modular.h
  lib/jxl/quant_weights.cc
  lib/jxl/toc.cc
Labels: decoder, CI:full, progressive

#358 handle case when jbrd fails at encoding
  tools/cjxl_main.cc
Labels: cjxl

#868 allow photon noise in modular mode
  lib/jxl/enc_frame.cc
  lib/jxl/enc_heuristics.cc
Labels: encoder

#866 update software support list
  doc/software_support.md
Labels: documentation

#872 Fix forgetting to destroy the decoder
  lib/jxl/encode_test.cc
Labels: testing

#831 API proposal: JxlDecoderSetCoalescing
  CHANGELOG.md
  lib/CMakeLists.txt
  lib/include/jxl/codestream_header.h
  lib/include/jxl/decode.h
  lib/jxl/dec_frame.cc
  lib/jxl/dec_frame.h
  lib/jxl/dec_params.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: decoder, api

#878 fix shadow variable in dec_patch_dictionary.cc
  lib/jxl/dec_patch_dictionary.cc
Labels: cleanup

#874 cleanups by maddin200
  lib/extras/codec_apng.cc
  lib/jxl/enc_noise.cc
  tools/jxl_emcc.cc
Labels: cleanup

#875 build gdk-pixbuf plugin when building for MSYS
  plugins/CMakeLists.txt
Labels: building/portability

#855 Add find module for hwy
  AUTHORS
  CMakeLists.txt
  cmake/FindHWY.cmake
  third_party/CMakeLists.txt
Labels: building/portability

#864 Fix configuration of a static MSVC build
  CMakeLists.txt
Labels: building/portability

#903 Bake-in unpublished API.
  lib/jxl/decode.cc
  tools/djxl_fuzzer.cc
Labels: fuzzerbug, api, testing

#916 fix JxlEncoderOptionsSetDistance
  lib/jxl/encode.cc
Labels: bug, encoder

#860 Refactor enc_color_management as the implementation of a C interface
  lib/include/jxl/cms_interface.h
  lib/include/jxl/decode.h
  lib/jxl/color_management_test.cc
  lib/jxl/enc_color_management.cc
  lib/jxl/enc_color_management.h
  lib/jxl/enc_image_bundle.cc
  lib/lib.gni
Labels: enhancement, encoder, api

#898 Add find module for brotli
  cmake/FindBrotli.cmake
  third_party/CMakeLists.txt
Labels: building/portability
