Repository libjxl/libjxl, pull requests merged in 2021-08, with the labels that each got.

#412 Fix for division by zero in masking
  lib/jxl/enc_adaptive_quantization.cc
Labels: bug, merge-0.5

#473 refactor and fix patch frame encoding
  lib/jxl/enc_frame.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/enc_patch_dictionary.h
Labels: encoder, encoder quality, regression, density

#479 Fix patch decoding fuzzer-found slow behaviour.
  lib/jxl/dec_patch_dictionary.cc
Labels: decoder, fuzzerbug, speedup

#480 print error when encountering non-recompressable (cmyk or corrupt) JPEG
  lib/extras/codec_jpg.cc
Labels: cjxl

#488 Add libjxl_extras to lib.gni and build_cleaner.py
  lib/jxl_extras.cmake
  lib/lib.gni
  tools/build_cleaner.py
Labels: building/portability

#481 flag to stop parsing options, fixes #433
  tools/cmdline.cc
  tools/cmdline.h
Labels: cjxl, djxl

#453 Update GIMP plugin to use public API and add save dialog
  plugins/gimp/CMakeLists.txt
  plugins/gimp/common.cc
  plugins/gimp/common.h
  plugins/gimp/file-jxl-load.cc
  plugins/gimp/file-jxl-load.h
  plugins/gimp/file-jxl-save.cc
  plugins/gimp/file-jxl-save.h
  plugins/gimp/file-jxl.cc
Labels: plugin

#519 Rewrite the GDK-Pixbuf plugin.
  plugins/gdk-pixbuf/CMakeLists.txt
  plugins/gdk-pixbuf/README.md
  plugins/gdk-pixbuf/loaders_test.cache
  plugins/gdk-pixbuf/pixbufloader-jxl.c
  third_party/skcms.cmake
Labels: plugin

#523 allow effort 1,2 in encode api
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
Labels: encoder, api

#521 tweak size header encoding (512x256 can be 'small' too)
  lib/jxl/headers.cc
Labels: encoder

#510 Speedup spline rendering by >10x with large splines
  lib/jxl/dec_frame.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/splines.cc
  lib/jxl/splines.h
  lib/jxl/splines_gbench.cc
  lib/jxl/splines_test.cc
  third_party/testdata/jxl/blending/grayscale_patches_on_splines.png
  third_party/testdata/jxl/splines.png
Labels: decoder, speedup

#527 Move gdk-pixbuf header to avoid size_t issues.
  plugins/gdk-pixbuf/pixbufloader-jxl.c
Labels: CI:full
