Repository libjxl/libjxl, pull requests merged in 2021-07, with the labels that each got.

#253 Removing discontinuous butteraugli-based heuristic
  lib/jxl/enc_ac_strategy.cc
Labels: cleanup, encoder quality

#243 Always define the fuzzer build targets
  lib/jxl/decode.cc
  tools/CMakeLists.txt
Labels: building/portability, fuzzerbug

#260 fix overflow in fwd palette
  lib/jxl/modular/transform/enc_palette.cc
Labels: bug, encoder

#259 Allocate output in case of rasterisation of partially-decoded DC
  lib/jxl/dec_frame.cc
Labels: decoder, progressive

#267 Improve failure reporting in djxl
  tools/djxl.cc
  tools/djxl_main.cc
Labels: djxl

#268 Code combing around JPEG channel mapping.
  lib/jxl/dec_frame.cc
  lib/jxl/dec_group.cc
Labels: cleanup

#250 Encoder: override color_transform for grayscale JPEG images with AdobeRGB ICC.
  lib/jxl/jpeg/enc_jpeg_data.cc
Labels: bug, encoder

#283 Remove ancient encoder flag
  lib/jxl/enc_params.h
Labels: cleanup

#7 updated 2 links
  README.md
Labels: documentation

#287 Add Image initialization expectations to YCbCrUpsampling
  lib/jxl/dec_reconstruct.cc
Labels: CI:full

#300 Get rid of fmemopen in codec_apng.
  lib/extras/codec_apng.cc
Labels: cjxl

#304 Build with gcc-8 in release mode in PRs.
  .github/workflows/build_test.yml
Labels: building/portability

#210 make modular transform checks tighter and fix nb_meta_channels bug
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/transform.cc
Labels: bug, decoder, fuzzerbug

#303 Relax x0 % kPaddingXRound requirement in FilterPipeline
  lib/jxl/dec_reconstruct.cc
  lib/jxl/epf.cc
  lib/jxl/epf.h
  lib/jxl/filters.cc
  lib/jxl/filters.h
Labels: CI:full

#305 fix psd decoder bug
  lib/extras/codec_psd.cc
Labels: cjxl

#322 less ringing
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
Labels: encoder quality

#215 improve benchmark_xl output a bit
  lib/jxl/aux_out.h
  lib/jxl/enc_ac_strategy.cc
  tools/benchmark/benchmark_stats.cc
  tools/benchmark/benchmark_stats.h
  tools/benchmark/benchmark_xl.cc
Labels: cleanup

#328 Add decoder API changes to changelog
  CHANGELOG.md
Labels: api, documentation, merge-0.5

#324 Bump version number to 0.5.0
  CHANGELOG.md
  debian/changelog
  lib/CMakeLists.txt
  lib/lib.gni
Labels: merge-0.5

#331 fuzz / bitstream bug: squeezing meta channnels
  lib/jxl/modular/transform/squeeze.cc
Labels: bug, decoder, fuzzerbug, merge-0.5

#340 Update CHANGELOG.md
  CHANGELOG.md
Labels: merge-0.5

#205 avoid full modular image copy
  lib/jxl/dec_frame.cc
  lib/jxl/dec_modular.cc
  lib/jxl/dec_modular.h
  lib/jxl/modular/transform/rct.h
  lib/jxl/modular/transform/transform.cc
Labels: decoder, speedup

#343 Fix decode_test
  lib/jxl/decode_test.cc
Labels: CI:full, bug, building/portability, merge-0.5

#325 Support extra channel output
  lib/include/jxl/decode.h
  lib/include/jxl/types.h
  lib/jxl/dec_external_image.cc
  lib/jxl/dec_external_image.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  tools/djxl_fuzzer.cc
Labels: api, decoder

#327 New fuzzing documentation
  README.md
  doc/fuzzing.md
Labels: documentation, fuzzerbug

#348 Fuzz: Fix ModularImageToDecodedRect crop and add checks
  lib/jxl/dec_modular.cc
Labels: decoder, fuzzerbug

#356 cjxl exit codes
  tools/cjxl_main.cc
Labels: cjxl

#352 Fuzz: Fix Rect rounding error decoding extra channels.
  lib/jxl/dec_modular.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/dec_upsample.cc
Labels: merge-0.5

#355 More bits for red and blue areas
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/jxl_test.cc
  tools/optimizer/simplex_fork.py
Labels: encoder quality

#366 Initialize all X and Y padding on extra channels in msan and oss-fuzz.
  lib/jxl/dec_frame.cc
Labels: CI:full

#365 fix use_full_image==false case
  lib/jxl/dec_modular.cc
Labels: bug, decoder, fuzzerbug

#370 Fuzz: Update the nb_meta_channels in squeeze when applying.
  lib/jxl/modular/transform/squeeze.cc
Labels: fuzzerbug, merge-0.5

#371 Fuzz: Return error if Gaborish weights lead to invalid kernel.
  lib/jxl/adaptive_reconstruction_test.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/filters.cc
  lib/jxl/filters.h
  tools/epf.cc
Labels: decoder

#376 Fuzz: Prevent divide by zero in Interpolate.
  lib/jxl/quant_weights.cc
Labels: fuzzerbug, merge-0.5

#368 Fuzz: Fix out of bounds access in squeeze channels
  lib/jxl/modular/transform/squeeze.cc
Labels: fuzzerbug, merge-0.5

#373 fix modular nb_meta_channels counter
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/transform.cc
Labels: fuzzerbug, merge-0.5

#375 Fix division through zero issue in AdaptToXYZD50
  lib/jxl/color_encoding_internal.cc
Labels: decoder, fuzzerbug, merge-0.5

#379 fuzz: fix assert in the exotic case of doing palette on palettes
  lib/jxl/modular/transform/palette.h
Labels: fuzzerbug, merge-0.5

#380 fuzz: return early when there is no modular data to decode
  lib/jxl/dec_modular.cc
  lib/jxl/dec_modular.h
Labels: fuzzerbug, merge-0.5

#211 Splines: skip DrawGaussian when sigma is 0, prevents possible divide-by-zero
  AUTHORS
  lib/jxl/splines.cc
Labels: bug, decoder
