Repository libjxl/libjxl, pull requests merged in 2021-09, with the labels that each got.

#337 Fix clang-5 warnings
  lib/CMakeLists.txt
  lib/jxl/aux_out.h
  lib/jxl/enc_detect_dots.cc
  lib/jxl/enc_dot_dictionary.cc
  lib/jxl/enc_icc_codec.cc
  lib/jxl/enc_modular.cc
  lib/jxl/encode_internal.h
  lib/jxl/epf.cc
  lib/jxl/frame_header.h
  lib/jxl/icc_codec_common.cc
  lib/jxl/icc_codec_common.h
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/encoding/encoding.cc
  lib/jxl/modular/options.h
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/palette.h
  lib/jxl/quant_weights.cc
  tools/benchmark/benchmark_codec_jpeg.cc
Labels: building/portability

#398 Add transforms fuzzer.
  tools/CMakeLists.txt
  tools/ossfuzz-build.sh
  tools/transforms_fuzzer.cc
Labels: fuzzerbug

#526 Simplifying stock palette indexing
  lib/jxl/modular/transform/palette.h
Labels: speedup, cleanup

#537 Stop marking all other symbols as local in the .version file
  lib/jxl/jxl.version
Labels: building/portability

#532 Add pipeline executions that allow ssh access.
  .github/workflows/debug_ci.yml
Labels: meta repo

#517 Edit Some Documents
  README.md
  doc/developing_in_debian.md
  doc/developing_in_docker.md
  doc/developing_in_windows_msys.md
  doc/developing_with_crossroad.md
Labels: documentation

#529 Implement animation support in the GDK plugin.
  plugins/gdk-pixbuf/pixbufloader-jxl.c
Labels: plugin

#534 Auto resample for high distance
  lib/jxl/enc_file.cc
  lib/jxl/enc_params.h
  tools/cjxl.cc
Labels: cjxl, encoder quality

#535 make encode api not ignore orientation field
  CHANGELOG.md
  examples/encode_oneshot.cc
  lib/include/jxl/codestream_header.h
  lib/include/jxl/encode.h
  lib/jxl/decode.cc
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
  lib/jxl/test_utils.h
Labels: encoder, api

#554 make "cjxl - -" encode stdin to stdout
  lib/jxl/base/cache_aligned.cc
  lib/jxl/base/file_io.h
  tools/cmdline.cc
Labels: cjxl, djxl

#551 Remove JPEG's DecodeTarget parameter.
  lib/extras/codec.cc
  lib/extras/codec_jpg.cc
  lib/extras/codec_jpg.h
  lib/jxl/decode_test.cc
  lib/jxl/jxl_test.cc
  tools/djxl.cc
  tools/fuzzer_corpus.cc
Labels: cjxl, cleanup

#547 add list of applications that use libjxl
  README.md
  doc/software_support.md
Labels: documentation

#556 Add release packages for debian testing/unstable.
  .github/workflows/release.yaml
Labels: building/portability

#573 GIMP plugin: Link against the shared library.
  plugins/gimp/CMakeLists.txt
Labels: building/portability

#572 Update changelog for v0.6
  CHANGELOG.md
Labels: merge-0.6

#525 GIMP Plugin Updates and Fixes
  plugins/gimp/file-jxl-load.cc
  plugins/gimp/file-jxl-save.cc
Labels: plugin

#562 allow combination of float + XYB in modular mode
  CHANGELOG.md
  lib/jxl/dec_modular.cc
  lib/jxl/enc_modular.cc
  lib/jxl/encode.cc
  lib/jxl/frame_header.cc
  tools/cjxl.cc
Labels: bug, encoder, api, merge-0.6

#575 Implement cmake's BUILD_SHARED_LIBS setting.
  CMakeLists.txt
  lib/jxl.cmake
  lib/jxl_threads.cmake
Labels: building/portability

#595 Support compiling GIMP plugin with glib < 2.62
  plugins/gimp/file-jxl-save.cc
Labels: building/portability, plugin

#600 silently fail on non-JPEGs
  lib/extras/codec_jpg.cc
Labels: cjxl

#605 Generate readthedocs.io sphinx documentation for the C API reference.
  .github/workflows/build_test.yml
  .readthedocs.yaml
  CMakeLists.txt
  doc/api.txt
  doc/sphinx/api.rst
  doc/sphinx/api_butteraugli.rst
  doc/sphinx/api_common.rst
  doc/sphinx/api_decoder.rst
  doc/sphinx/api_encoder.rst
  doc/sphinx/api_threads.rst
  doc/sphinx/conf.py
  doc/sphinx/index.rst
  doc/sphinx/requirements.txt
  lib/include/jxl/butteraugli.h
  lib/include/jxl/butteraugli_cxx.h
  lib/include/jxl/codestream_header.h
  lib/include/jxl/color_encoding.h
  lib/include/jxl/decode.h
  lib/include/jxl/decode_cxx.h
  lib/include/jxl/encode.h
  lib/include/jxl/encode_cxx.h
  lib/include/jxl/memory_manager.h
  lib/include/jxl/parallel_runner.h
  lib/include/jxl/resizable_parallel_runner.h
  lib/include/jxl/resizable_parallel_runner_cxx.h
  lib/include/jxl/thread_parallel_runner.h
  lib/include/jxl/thread_parallel_runner_cxx.h
  lib/include/jxl/types.h
Labels: documentation, api

#601 allow gif with out-of-bounds bg color
  lib/extras/codec_gif.cc
Labels: cjxl

#618 fuzzer: integer overflow in MA decoding
  lib/jxl/modular/encoding/dec_ma.cc
Labels: decoder, fuzzerbug

#621 add a test for permute-only RCT and custom WP
  lib/jxl/modular_test.cc
Labels: testing

#616 add format overview documentation
  README.md
  doc/format_overview.md
Labels: documentation

#619 Remove Fields::Name() strings from non-debug builds.
  lib/jxl/color_encoding_internal.h
  lib/jxl/dec_ans.h
  lib/jxl/field_encodings.h
  lib/jxl/fields.cc
  lib/jxl/fields_test.cc
  lib/jxl/frame_header.h
  lib/jxl/headers.h
  lib/jxl/image_metadata.h
  lib/jxl/jpeg/jpeg_data.h
  lib/jxl/loop_filter.h
  lib/jxl/modular/encoding/context_predict.h
  lib/jxl/modular/encoding/encoding.h
  lib/jxl/modular/modular_image.cc
  lib/jxl/modular/transform/transform.h
  lib/jxl/quantizer.h
Labels: cleanup

#617 add custom squeeze encode option (just for testing atm)
  lib/jxl/enc_modular.cc
  lib/jxl/enc_params.h
  lib/jxl/modular_test.cc
Labels: encoder, testing

#622 add test for delta-palette
  lib/jxl/modular_test.cc
Labels: testing

#620 deduplicate PrintTree and move enc-only debug stuff to a new file
  lib/jxl.cmake
  lib/jxl/enc_modular.cc
  lib/jxl/modular/encoding/context_predict.h
  lib/jxl/modular/encoding/enc_debug_tree.cc
  lib/jxl/modular/encoding/enc_debug_tree.h
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/encoding/enc_encoding.h
  lib/jxl/modular/options.h
  lib/lib.gni
  tools/jxl_from_tree.cc
Labels: cleanup

#631 adjust threshold to make msan test pass
  lib/jxl/modular_test.cc
Labels: testing

#627 allow changing predictor used in delta palette
  lib/jxl/enc_modular.cc
  lib/jxl/enc_modular.h
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular_test.cc
Labels: enhancement, encoder, cleanup, testing

#629 fix and (better) test progressive decode
  lib/jxl/adaptive_reconstruction_test.cc
  lib/jxl/dec_frame.cc
  lib/jxl/dec_reconstruct.cc
  lib/jxl/dec_reconstruct.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  tools/epf.cc
Labels: bug, decoder, progressive, testing

#635 cleanup undo_transforms
  lib/jxl/dec_modular.cc
  lib/jxl/enc_modular.cc
  lib/jxl/modular/encoding/encoding.cc
  lib/jxl/modular/encoding/encoding.h
  lib/jxl/modular/modular_image.cc
  lib/jxl/modular/modular_image.h
  tools/transforms_fuzzer.cc
Labels: cleanup

#599 do not set default squeeze params in InvSqueeze
  lib/jxl/jxl_test.cc
  lib/jxl/modular/transform/enc_squeeze.cc
  lib/jxl/modular/transform/squeeze.cc
Labels: cleanup

#577 move encode-only code out of dec_patch_dictionary.h
  lib/jxl/dec_patch_dictionary.h
  lib/jxl/enc_detect_dots.h
  lib/jxl/enc_dot_dictionary.h
  lib/jxl/enc_patch_dictionary.h
Labels: cleanup

#640 Allow delta palette in >8-bit images.
  lib/jxl/modular/transform/enc_palette.cc
Labels: enhancement, encoder

#644 remove unused function in image.cc
  lib/jxl/image.cc
Labels: cleanup

#645 add test for (progressive) decode of image using upsampling
  lib/jxl/decode_test.cc
Labels: progressive, testing

#641 Allow setting more boxes after decoder finished
  lib/include/jxl/decode.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: decoder, api, container/metadata

#652 fix case where the global modular image is used after all
  lib/jxl/dec_modular.cc
Labels: bug, decoder, regression, merge-0.6

#653 remove stale documentation
  doc/color_management.md
  lib/jxl/docs/dc_predictor.md
  lib/jxl/docs/entropy_coding_basic.md
  lib/jxl/docs/file_format.md
  lib/jxl/docs/upsample.md
Labels: documentation

#654 exclude more test stuff from coverage report
  ci.sh
Labels: cleanup, testing

#656 silly typo in excluding test-only stuff
  ci.sh
Labels: testing

#655 fix allocation not being done before use in some cases
  lib/jxl/dec_frame.cc
  lib/jxl/dec_frame.h
  lib/jxl/dec_group.cc
Labels: bug, regression, progressive, merge-0.6

#598 Add several options to the encoder api
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
Labels: encoder, api

#658 cleanup deprecated += in BitWriter
  lib/jxl/enc_bit_writer.cc
  lib/jxl/enc_bit_writer.h
Labels: cleanup

#660 some more enc_bit_writer cleanup
  lib/jxl/enc_bit_writer.h
Labels: cleanup

#659 remove uint24
  lib/jxl/base/byte_order.h
  lib/jxl/dec_external_image.cc
  lib/jxl/enc_external_image.cc
Labels: cleanup

#662 add test for lossless modular handling of custom float data
  lib/jxl/modular_test.cc
Labels: testing

#651 try RCTs and custom WP also for single-group images
  lib/jxl/enc_modular.cc
  lib/jxl/modular_test.cc
Labels: encoder, density

#672 cleanup image_bundle and enc_image_bundle
  lib/extras/codec_exr.cc
  lib/extras/codec_jpg.cc
  lib/extras/codec_pgx.cc
  lib/extras/codec_png.cc
  lib/extras/codec_pnm.cc
  lib/jxl/enc_butteraugli_comparator.cc
  lib/jxl/enc_comparator.cc
  lib/jxl/enc_image_bundle.cc
  lib/jxl/enc_xyb.cc
  lib/jxl/image_bundle.h
  tools/benchmark/benchmark_codec_webp.cc
Labels: cleanup
