Repository libjxl/libjxl, pull requests merged in 2022-07, with the labels that each got.

#1562 Disable failing hwy tests on Windows build.
  .github/workflows/build_test.yml
Labels: CI:full

#1567 Lower the minimum required Clang version to 5
  CMakeLists.txt
Labels: CI:full

#1372 Cross-compile inside Debian docker
  .github/workflows/build_test_cross.yml
  plugins/gdk-pixbuf/CMakeLists.txt
  tools/CMakeLists.txt
  tools/roundtrip_test.sh
Labels: building/portability, CI:full

#1406 follow spec regarding shift brackets in multi-pass modular
  lib/jxl/frame_header.cc
  lib/jxl/frame_header.h
Labels: bug, documentation, decoder, encoder, progressive, spec

#1371 deprecate JxlDecoderDefaultPixelFormat
  lib/include/jxl/decode.h
Labels: decoder, api

#1626 Fix ASAN crash after #1624
  lib/jxl/alpha.cc
  lib/jxl/alpha.h
  lib/jxl/jxl_test.cc
  lib/jxl/render_pipeline/stage_write.cc
Labels: CI:full

#1631 Remove intermediate CodecInOut stage in ppf->png encoder.
  lib/extras/codec.cc
  lib/extras/codec_test.cc
  lib/extras/dec/decode.cc
  lib/extras/dec/decode.h
  lib/extras/enc/apng.cc
  lib/extras/enc/apng.h
  lib/extras/enc/encode.cc
  lib/extras/enc/encode.h
  lib/extras/enc/pnm.cc
  lib/extras/enc/pnm.h
  lib/extras/packed_image.h
  lib/extras/packed_image_convert.cc
  lib/jxl/test_utils.h
  tools/benchmark/benchmark_codec_custom.cc
  tools/benchmark/benchmark_codec_png.cc
Labels: CI:full

#1635 Fix float32 small/large cube implicit palette value scaling.
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/palette.h
Labels: CI:full

#1638 Add tighter memory usage limits on patch dictionary.
  lib/jxl/dec_patch_dictionary.cc
  lib/jxl/dec_patch_dictionary.h
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/enc_patch_dictionary.h
Labels: CI:full

#1647 Fix MSAN bug found by fuzzers.
  lib/jxl/dec_frame.cc
  lib/jxl/dec_modular.cc
Labels: CI:full

#1650 Fix MSAN test failure.
  lib/jxl/dec_frame.cc
  tools/djxl_fuzzer_test.cc
Labels: CI:full

#1656 Parametrize slowest tests
  lib/jxl/data_parallel_test.cc
  lib/jxl/decode_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/passes_test.cc
  tools/djxl_fuzzer_test.cc
Labels: CI:full
