Repository libjxl/libjxl, pull requests merged in 2022-11, with the labels that each got.

#1866 Make jpeg decoder more self-contained.
  lib/extras/dec_group_jpeg.cc
  lib/extras/dec_group_jpeg.h
Labels: CI:full

#1875 XYB-jpeg: jpeg-specific clustering and more progression.
  lib/extras/encode_jpeg.cc
Labels: CI:full

#1881 don't compile debug print tree code
  lib/jxl/enc_modular.cc
Labels: bug

#1863 plugins/gimp: Support for decoding animations
  AUTHORS
  plugins/gimp/file-jxl-load.cc
Labels: CI:full

#1879 Use libjpeg's source manager api in streaming jpeg decoder.
  lib/extras/decode_jpeg.cc
  lib/extras/decode_jpeg.h
  lib/extras/decode_jpeg_test.cc
  lib/jxl_extras.cmake
  lib/lib.gni
  tools/build_cleaner.py
Labels: CI:full

#1908 Fix WASM test
  lib/jxl_tests.cmake
  tools/wasm_demo/CMakeLists.txt
  tools/wasm_demo/jxl_decoder_test.js
Labels: CI:full

#1925 fix hshift/vshift of metachannels
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/squeeze.cc
Labels: CI:full, spec

#1919 remove deprecated or dead code
  lib/include/jxl/decode.h
  lib/jxl/alpha.cc
  lib/jxl/alpha.h
  lib/jxl/dec_external_image.cc
  lib/jxl/dec_external_image.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_params.h
  lib/jxl/speed_tier_test.cc
  tools/benchmark/benchmark_codec_jxl.cc
Labels: cleanup
