Repository libjxl/libjxl, pull requests merged in 2022-09, with the labels that each got.

#1724 Use low-memory render pipeline for all callback data types.
  lib/jxl/base/byte_order.h
  lib/jxl/dec_cache.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.h
  lib/jxl/decode.cc
  lib/jxl/render_pipeline/stage_write.cc
  lib/jxl/render_pipeline/stage_write.h
Labels: CI:full

#1729 Fix broken tests caused by #1727.
  lib/jxl/color_management_test.cc
  lib/jxl/decode_test.cc
Labels: CI:full

#1730 SIMDify interleaving the RGB(A) pixels for the decoder callback.
  lib/jxl/render_pipeline/stage_write.cc
Labels: CI:full

#1733 Unify the pixel callback and image buffer write stages.
  lib/jxl/base/byte_order.h
  lib/jxl/dec_cache.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/render_pipeline/stage_write.cc
  lib/jxl/render_pipeline/stage_write.h
Labels: CI:full

#1738 Fix uninitialized value in jpeg benchmark.
  tools/benchmark/benchmark_codec_jpeg.cc
Labels: CI:full

#1740 Handle extra channels in WriteToOutputStage.
  lib/jxl/dec_cache.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/render_pipeline/stage_write.cc
  lib/jxl/render_pipeline/stage_write.h
Labels: CI:full

#834 export version information in headers
  AUTHORS
  CHANGELOG.md
  lib/include/jxl/decode.h
  lib/jxl.cmake
  lib/jxl/version.h.in
Labels: api

#1752 Improve PNM codec output and ppf bit depth handling for djxl.
  lib/extras/codec_test.cc
  lib/extras/dec/jxl.cc
  lib/extras/dec/pnm.cc
  lib/extras/enc/apng.cc
  lib/extras/enc/encode.cc
  lib/extras/enc/encode.h
  lib/extras/enc/pnm.cc
  lib/extras/packed_image.h
  lib/extras/packed_image_convert.cc
  lib/jxl/jxl_test.cc
  tools/djxl_main.cc
Labels: CI:full

#1766 always inclue patch in bump_version script
  ci.sh
Labels: merge-0.7

#1673 explain tags for branch-off points
  doc/release.md
Labels: merge-0.7

#1777 Relax some of the expectations on compressed file sizes.
  lib/extras/dec/jxl.cc
  lib/jxl/jxl_test.cc
  lib/jxl/test_image.h
  lib/jxl/testdata.h
Labels: CI:full

#1786 Convert more tests to use ppf input + alpha bit depth bugfix.
  lib/extras/enc/jxl.cc
  lib/jxl/jxl_test.cc
  lib/jxl/test_image.h
  lib/jxl/test_utils.h
Labels: CI:full

#1791 Convert more tests to use ppf input.
  lib/extras/packed_image.h
  lib/jxl/codec_y4m_testonly.cc
  lib/jxl/codec_y4m_testonly.h
  lib/jxl/jxl_test.cc
  lib/jxl/test_image.h
  lib/jxl/test_utils.h
  lib/jxl_tests.cmake
  lib/lib.gni
Labels: CI:full

#1417 remove detailed error codes from jpeg data reader; remove max size limit
  lib/jxl/jpeg/enc_jpeg_data_reader.cc
  lib/jxl/jpeg/jpeg_data.cc
  lib/jxl/jpeg/jpeg_data.h
Labels: encoder, cleanup

#1762 remove discontinuity in DC approach at d2
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_cache.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
Labels: encoder quality

#1799 Adjust roundtrip test expectations.
  lib/jxl/decode_test.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
Labels: CI:full
