Repository libjxl/libjxl, pull requests merged in 2022-03, with the labels that each got.

#1190 write png end for composite still
  lib/extras/enc/apng.cc
Labels: djxl

#1148 SIMDify inverse YCoCg
  lib/jxl/modular/transform/rct.cc
Labels: decoder, speedup

#1213 Homogenise noise seeding
  .github/workflows/conformance.yml
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.cc
  lib/jxl/dec_noise.cc
  lib/jxl/dec_noise.h
  lib/jxl/xorshift128plus-inl.h
  tools/add_noise.cc
Labels: decoder, spec

#1229 remove duplicate else if
  tools/djxl_ng_main.cc
Labels: cleanup

#1227 use actual num_channels instead of guessing from color encoding
  lib/extras/packed_image_convert.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_external_image.cc
  lib/jxl/enc_external_image.h
  lib/jxl/enc_external_image_gbench.cc
  lib/jxl/enc_external_image_test.cc
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_utils.h
  tools/benchmark/benchmark_codec_avif.cc
  tools/benchmark/benchmark_codec_webp.cc
  tools/fuzzer_corpus.cc
Labels: encoder, api

#1235 Cleanup enc params
  lib/jxl/enc_params.h
Labels: cleanup

#1022 enc buffer api: check if buffer size matches
  lib/include/jxl/encode.h
  lib/jxl/enc_external_image.cc
Labels: encoder, api

#1027 assume RGB pixels are all-opaque (if there's alpha)
  lib/extras/packed_image_convert.cc
  lib/include/jxl/encode.h
  lib/jxl/enc_external_image.cc
Labels: encoder, api

#1267 fix accuracy of float2int / int2float and add test
  lib/jxl/dec_modular.cc
  lib/jxl/enc_modular.cc
  lib/jxl/modular_test.cc
Labels: testing

#1256 fix #1244 (spurious error messages doing non-lossy palette)
  lib/jxl/modular/transform/enc_palette.cc
Labels: encoder, speedup, regression

#1194 add brotli_effort option
  lib/include/jxl/encode.h
  lib/jxl/decode_test.cc
  lib/jxl/enc_params.h
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/jpeg/enc_jpeg_data.cc
  lib/jxl/jpeg/enc_jpeg_data.h
  lib/jxl/jxl_test.cc
  tools/cjxl.cc
  tools/cjxl_main.cc
  tools/cjxl_ng_main.cc
  tools/fuzzer_corpus.cc
Labels: enhancement, cjxl, encoder, api

#1263 modular_16 and a cparam to conform to level restrictions
  lib/jxl/dec_file.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_params.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
  lib/jxl/roundtrip_test.cc
Labels: encoder

#960 Use CMAKE_INSTALL_DATADIR to install man pages
  AUTHORS
  CMakeLists.txt
Labels: building/portability

#1247 fail earlier when level is too low
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
Labels: encoder, api

#544 better handling of exif (in particular orientation)
  lib/extras/enc/apng.cc
  lib/extras/enc/jpg.cc
  lib/jxl.cmake
  lib/jxl/enc_file.cc
  lib/jxl/exif.cc
  lib/jxl/exif.h
  lib/lib.gni
Labels: bug, cjxl, djxl, container/metadata, merge-0.6

#1271 remove psd input
  lib/extras/codec.cc
  lib/extras/codec_psd.cc
  lib/extras/codec_psd.h
  lib/extras/dec/decode.cc
  lib/extras/dec/decode.h
  lib/jxl/encode_test.cc
  lib/jxl_extras.cmake
  lib/lib.gni
Labels: cjxl, cleanup

#1275 remove modular quality
  lib/jxl/decode_test.cc
  lib/jxl/enc_cache.cc
  lib/jxl/enc_file.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_modular.h
  lib/jxl/enc_params.h
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/encode.cc
  lib/jxl/jxl_test.cc
  lib/jxl/modular_test.cc
  lib/jxl/patch_dictionary_test.cc
  lib/jxl/render_pipeline/render_pipeline_test.cc
  lib/jxl/roundtrip_test.cc
  tools/benchmark/benchmark_codec.cc
  tools/benchmark/benchmark_codec_jxl.cc
  tools/cjxl.cc
  tools/fuzzer_corpus.cc
Labels: encoder quality, cleanup

#1279 fix ppm input where bitdepth is not 8 or 16
  lib/extras/dec/pnm.cc
  lib/extras/packed_image.h
  lib/extras/packed_image_convert.cc
Labels: cjxl, regression

#1286 noise seeding: match frame index of jxli box
  lib/jxl/dec_frame.cc
Labels: decoder, container/metadata, spec

#1157 Faster unsqueeze / lossy modular
  lib/jxl/modular/encoding/context_predict.h
  lib/jxl/modular/encoding/encoding.cc
  lib/jxl/modular/transform/squeeze.cc
  lib/jxl/modular/transform/squeeze.h
  lib/jxl/simd_util-inl.h
Labels: decoder, speedup

#1301 More flattening
  lib/jxl/modular/transform/squeeze.cc
Labels: CI:full

#1166 Pthread dependencies
  lib/jxl.cmake
Labels: building/portability

#1304 Patch frame quant
  lib/jxl/enc_modular.cc
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/jxl_test.cc
Labels: encoder, encoder quality

#1305 Refactor padding calculation to improve readability.
  lib/jxl/image.h
  lib/jxl/render_pipeline/low_memory_render_pipeline.cc
Labels: CI:full

#1309 Fix q100
  tools/cjxl.cc
Labels: cjxl

#612 Add brotli to deps.sh
  AUTHORS
  deps.sh
Labels: building/portability
