Repository libjxl/libjxl, pull requests merged in 2022-10, with the labels that each got.

#1807 Add separate data type and bit depth argument to image converter.
  lib/extras/packed_image_convert.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_external_image.cc
  lib/jxl/enc_external_image.h
  lib/jxl/enc_external_image_gbench.cc
  lib/jxl/enc_external_image_test.cc
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_utils.h
  tools/benchmark/benchmark_codec_avif.cc
  tools/benchmark/benchmark_codec_webp.cc
  tools/fuzzer_corpus.cc
Labels: CI:full

#1812 Add API functions for setting input/output bit depth.
  CHANGELOG.md
  lib/extras/dec/jxl.cc
  lib/extras/dec/jxl.h
  lib/extras/decode_jpeg.cc
  lib/extras/enc/jxl.cc
  lib/extras/enc/jxl.h
  lib/include/jxl/decode.h
  lib/include/jxl/encode.h
  lib/include/jxl/types.h
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.h
  lib/jxl/decode.cc
  lib/jxl/enc_external_image.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/jxl_test.cc
  lib/jxl/render_pipeline/stage_write.cc
  lib/jxl/test_image.h
  lib/jxl/test_utils.h
Labels: CI:full

#1434 jxl_from_tree read and write to stdin and stdout
  tools/jxl_from_tree.cc
Labels: unrelated to 1.0

#1822 make butteraugli slightly more sensitive to low freq errors
  lib/jxl/butteraugli/butteraugli.cc
  lib/jxl/modular_test.cc
Labels: encoder quality

#1831 Update roundtrip test expectations.
  lib/jxl/jxl_test.cc
Labels: CI:full

#1784 run a2x.exe directly on MinGW
  CMakeLists.txt
Labels: CI:full

#1837 Compute optimal dequant biases assuming Laplacian AC distribution.
  lib/extras/dec_group_jpeg.cc
  lib/extras/dec_group_jpeg.h
  lib/extras/decode_jpeg.cc
Labels: CI:full

#1838 Check the sizes of extra channel backgrounds in blending stage.
  lib/jxl/frame_header.cc
  lib/jxl/render_pipeline/stage_blending.cc
Labels: CI:full

#1366 API only (proposal): set CMS and desired output color encoding in decoder
  lib/include/jxl/decode.h
Labels: enhancement, decoder, api
