Repository libjxl/libjxl, pull requests merged in 2022-08, with the labels that each got.

#1661 Remove djxl's dependence on libjxl internals.
  .github/workflows/conformance.yml
  lib/extras/codec.cc
  lib/extras/codec_test.cc
  lib/extras/dec/pnm.cc
  lib/extras/enc/apng.cc
  lib/extras/enc/encode.cc
  lib/extras/enc/encode.h
  lib/extras/enc/exr.cc
  lib/extras/enc/exr.h
  lib/extras/enc/jpg.cc
  lib/extras/enc/jpg.h
  lib/extras/enc/npy.cc
  lib/extras/enc/pgx.cc
  lib/extras/enc/pnm.cc
  lib/extras/enc/pnm.h
  lib/extras/exif.cc
  lib/extras/exif.h
  lib/extras/packed_image.h
  lib/extras/packed_image_convert.cc
  lib/jxl/codec_in_out.h
  lib/jxl/decode_test.cc
  lib/jxl/enc_external_image.cc
  lib/jxl/enc_external_image.h
  lib/jxl/enc_external_image_gbench.cc
  lib/jxl/enc_external_image_test.cc
  lib/jxl/exif.cc
  lib/jxl/exif.h
  lib/jxl/frame_header.h
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_utils.h
  lib/jxl_extras.cmake
  lib/jxl_tests.cmake
  lib/lib.gni
  tools/CMakeLists.txt
  tools/benchmark/benchmark_codec_avif.cc
  tools/benchmark/benchmark_codec_jpeg.cc
  tools/benchmark/benchmark_codec_jxl.cc
  tools/benchmark/benchmark_codec_webp.cc
  tools/cjxl_main.cc
  tools/djxl_main.cc
  tools/file_io.cc
  tools/file_io.h
  tools/fuzzer_corpus.cc
Labels: CI:full

#1597 Fix SVE compilation
  CMakeLists.txt
  lib/jxl/butteraugli/butteraugli.cc
  lib/jxl/compressed_dc.cc
  lib/jxl/convolve-inl.h
  lib/jxl/convolve_separable5.cc
  lib/jxl/convolve_separable7.cc
  lib/jxl/convolve_symmetric3.cc
  lib/jxl/convolve_symmetric5.cc
  lib/jxl/dct-inl.h
  lib/jxl/dec_external_image.cc
  lib/jxl/dec_group.cc
  lib/jxl/dec_modular.cc
  lib/jxl/dec_noise.cc
  lib/jxl/dec_tone_mapping-inl.h
  lib/jxl/dec_transforms-inl.h
  lib/jxl/dec_xyb-inl.h
  lib/jxl/dec_xyb.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_ar_control_field.cc
  lib/jxl/enc_butteraugli_pnorm.cc
  lib/jxl/enc_chroma_from_luma.cc
  lib/jxl/enc_cluster.cc
  lib/jxl/enc_color_management.cc
  lib/jxl/enc_detect_dots.cc
  lib/jxl/enc_entropy_coder.cc
  lib/jxl/enc_group.cc
  lib/jxl/enc_xyb.cc
  lib/jxl/fast_math-inl.h
  lib/jxl/gauss_blur.cc
  lib/jxl/modular/encoding/enc_ma.cc
  lib/jxl/modular/transform/rct.cc
  lib/jxl/modular/transform/squeeze.cc
  lib/jxl/quant_weights.cc
  lib/jxl/quantizer-inl.h
  lib/jxl/rational_polynomial-inl.h
  lib/jxl/rational_polynomial_test.cc
  lib/jxl/render_pipeline/stage_chroma_upsampling.cc
  lib/jxl/render_pipeline/stage_epf.cc
  lib/jxl/render_pipeline/stage_from_linear.cc
  lib/jxl/render_pipeline/stage_gaborish.cc
  lib/jxl/render_pipeline/stage_noise.cc
  lib/jxl/render_pipeline/stage_to_linear.cc
  lib/jxl/render_pipeline/stage_tone_mapping.cc
  lib/jxl/render_pipeline/stage_upsampling.cc
  lib/jxl/render_pipeline/stage_write.cc
  lib/jxl/render_pipeline/stage_ycbcr.cc
  lib/jxl/splines.cc
  lib/jxl/transfer_functions-inl.h
  lib/jxl/xorshift128plus-inl.h
  lib/jxl/xorshift128plus_test.cc
Labels: CI:full

#1651 Use an interval tree for looking up patches that intersect a row.
  lib/jxl/dec_patch_dictionary.cc
  lib/jxl/dec_patch_dictionary.h
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/enc_patch_dictionary.h
Labels: CI:full

#1691 Fix placement of JXL_DEPRECATED macros.
  lib/include/jxl/decode.h
  lib/include/jxl/encode.h
  lib/include/jxl/types.h
Labels: CI:full

#1702 Override brotli "no-install" policy.
  third_party/CMakeLists.txt
Labels: merge-0.7

#1704 Do not exclude brotli from "all"
  third_party/CMakeLists.txt
Labels: merge-0.7

#1705 Add SVE build to cross-matrix
  .github/workflows/build_test_cross.yml
  CMakeLists.txt
  lib/jxl/dec_noise.cc
Labels: CI:full, merge-0.7

#1711 tests: Make sure libjxl0.7 can still be found
  tools/CMakeLists.txt
Labels: merge-0.7
