Repository libjxl/libjxl, pull requests merged in 2022-05, with the labels that each got.

#1387 simplify/improve/correct box API documentation
  lib/include/jxl/decode.h
  lib/include/jxl/encode.h
Labels: documentation, api

#1350 jpeg recompression: preserve exif/xmp/jumbf
  lib/jxl/encode.cc
Labels: encoder, api, container/metadata

#1402 Refactor the low memory rendering pipeline and fix patch + noise combination.
  lib/jxl/dec_cache.cc
  lib/jxl/image.h
  lib/jxl/render_pipeline/low_memory_render_pipeline.cc
  lib/jxl/render_pipeline/render_pipeline_stage.h
  lib/jxl/render_pipeline/render_pipeline_test.cc
  lib/jxl/render_pipeline/stage_patches.cc
  lib/jxl/render_pipeline/stage_patches.h
Labels: decoder, cleanup, regression

#1411 Improvements/fixes for WASM builds
  .github/workflows/build_test.yml
  CMakeLists.txt
  ci.sh
  js-wasm-wrapper.sh
  lib/jxl/base/file_io.h
  lib/jxl/testdata.h
  lib/jxl_tests.cmake
  lib/threads/thread_parallel_runner_internal.cc
  tools/jxl_emcc.cc
Labels: CI:full

#1341 relax high bitdepth palette restriction and improve lossless float compression
  lib/jxl/enc_modular.cc
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular/transform/transform.cc
Labels: encoder, density, spec

#1392 implement JxlDecoderSetProgressiveDetail
  lib/include/jxl/decode.h
  lib/include/jxl/types.h
  lib/jxl/dec_frame.cc
  lib/jxl/dec_frame.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
Labels: decoder, api, progressive

#1418 add ffmpeg, krita, tachiyomi to list of software supporting jxl
  doc/software_support.md
Labels: documentation

#823 encoder api: error codes
  lib/include/jxl/encode.h
  lib/jxl/enc_modular.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/encode_test.cc
  lib/jxl/jpeg/jpeg_data.cc
  lib/jxl/jpeg/jpeg_data.h
  lib/jxl/test_utils.h
  tools/cjxl.cc
  tools/cjxl_ng_main.cc
Labels: encoder, api, container/metadata

#1421 Add Reference Links to Decoder Docs
  lib/include/jxl/decode.h
Labels: documentation

#1336 Attempt to implement the frame index box
  lib/jxl/decode.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
Labels: enhancement, container/metadata

#1428 fix range check for RCT
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
  tools/cjxl.cc
  tools/cjxl_ng_main.cc
Labels: encoder, spec
