Repository libjxl/libjxl, pull requests merged in 2022-04, with the labels that each got.

#1325 Try to fix "release" workflow
  lib/jxl_extras.cmake
Labels: CI:full

#1326 Deal with Schrödinger MSAN report
  lib/jxl/encode.cc
Labels: CI:full

#1312 Pnm max val log2
  lib/extras/dec/pnm.cc
  lib/extras/packed_image.h
  lib/jxl/bits_test.cc
  lib/jxl/enc_external_image.cc
Labels: post 1.0

#1338 fix pnm output for the non-multiple-of-8 bitdepth cases
  lib/extras/packed_image_convert.cc
Labels: djxl, regression

#1334 minor cleanup/fix
  lib/jxl/aux_out.h
  lib/jxl/dec_ans.cc
Labels: cleanup

#1351 attempt to fix release build
  .github/workflows/release.yaml
Labels: building/portability, CI:full

#1352 don't run fast_benchmark after coverage
  .github/workflows/build_test.yml
  ci.sh
Labels: testing

#1349 allow bigger png chunks
  lib/extras/dec/apng.cc
Labels: cjxl

#1359 Remove stale cases in which decoder fast paths were not supported.
  lib/jxl/dec_frame.h
Labels: cleanup

#1337 deprecate JXL_TYPE_BOOLEAN and JXL_TYPE_UINT32
  lib/extras/dec/pgx.cc
  lib/extras/dec/pnm.cc
  lib/extras/packed_image.h
  lib/include/jxl/encode.h
  lib/include/jxl/types.h
  lib/jxl/butteraugli_wrapper.cc
  lib/jxl/dec_external_image.cc
  lib/jxl/dec_external_image.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_external_image.cc
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_utils.h
Labels: CI:full, cleanup, api, leet

#1363 fix documentation bug in brob API
  lib/include/jxl/decode.h
Labels: documentation, decoder, api, container/metadata

#1364 Fix linking to system-wide gflags
  third_party/CMakeLists.txt
  tools/CMakeLists.txt
Labels: building/portability

#1367 simplify simd unsqueeze
  lib/jxl/modular/transform/squeeze.cc
Labels: decoder, speedup, cleanup

#1310 cjxl_ng: Extensive clean-up
  tools/cjxl_ng_main.cc
Labels: cjxl, cleanup

#1376 remove unused functions and add_noise tool
  lib/jxl/dec_noise.cc
  lib/jxl/dec_noise.h
  lib/jxl/dec_patch_dictionary.cc
  lib/jxl/dec_patch_dictionary.h
  tools/CMakeLists.txt
  tools/add_noise.cc
Labels: cleanup

#1375 don't fail to decode when num_patches is explicitly zero
  lib/jxl/dec_patch_dictionary.cc
Labels: bug, decoder

#1374 remove some unused image_ops functions
  lib/jxl/image.cc
  lib/jxl/image_ops.h
Labels: cleanup

#1373 make coverage run all tests, and only build it if it's going to make a report
  .github/workflows/build_test.yml
  lib/CMakeLists.txt
Labels: testing, post 1.0
