Repository libjxl/libjxl, pull requests merged in 2022-12, with the labels that each got.

#1941 Fix asan build.
  lib/jpegli/decode_api_test.cc
  lib/jpegli/decode_scan.cc
Labels: CI:full

#1937 jpegli: implement buffered image mode
  lib/jpegli/decode_api.cc
  lib/jpegli/decode_api_test.cc
Labels: CI:full

#1948 jpegli: implement raw data output mode
  .github/workflows/debug_ci.yml
  lib/jpegli/decode_api.cc
  lib/jpegli/decode_api_test.cc
  lib/jpegli/decode_internal.h
  lib/jpegli/render.cc
  lib/jpegli/render.h
  lib/jpegli/upsample.cc
  lib/jpegli/upsample.h
Labels: CI:full

#1949 Add libjpegli's libjpeg.so target to build/lib directory.
  lib/jpegli.cmake
Labels: CI:full

#1956 Fix CI, take 2
  .github/workflows/release.yaml
  lib/jxl/enc_ans.cc
  lib/jxl/progressive_split.h
  plugins/gdk-pixbuf/CMakeLists.txt
Labels: CI:full

#1967 jpegli: first version of encoder api
  .github/workflows/build_test.yml
  lib/jpegli.cmake
  lib/jpegli/common_api.cc
  lib/jpegli/dct.cc
  lib/jpegli/dct.h
  lib/jpegli/destination_manager.cc
  lib/jpegli/encode_api.cc
  lib/jpegli/encode_api_test.cc
  lib/jpegli/encode_internal.h
  lib/jpegli/entropy_coding.cc
  lib/jpegli/entropy_coding.h
  lib/jpegli/jpeg.version
  lib/jpegli/memory_manager.h
  lib/jpegli/quant.cc
  lib/jpegli/quant.h
  lib/jxl/enc_xyb.cc
  lib/jxl/enc_xyb.h
Labels: CI:full

#1977 attempt to fix tests
  lib/jxl/jxl_test.cc
Labels: CI:full

#1976 Fix fast-lossless on MSVC.
  lib/jxl/enc_fast_lossless.cc
Labels: building/portability

#1942 make cjxl input.jpg -d 3 do lossy recompression
  tools/cjxl_main.cc
Labels: cjxl

#1980 Workaround for --save-decompressed failing.
  tools/benchmark/benchmark_xl.cc
Labels: bug

#1982 no fast lossless animation yet
  lib/jxl/encode.cc
Labels: encoder, regression

#1984 Add SSIMULACRA2 to benchmark_xl
  tools/CMakeLists.txt
  tools/benchmark/benchmark_stats.cc
  tools/benchmark/benchmark_stats.h
  tools/benchmark/benchmark_xl.cc
Labels: encoder quality, testing

#1987 less ringing for anime
  lib/jpegli/encode_api_test.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/passes_test.cc
Labels: encoder quality

#1996 fix RoundtripSmallPatches et al.
  lib/jxl/decode_test.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#2005 improvements for red/green in AC strategy
  lib/jxl/decode_test.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/passes_test.cc
Labels: CI:full

#2007 improved precision with red/green handling
  lib/jxl/decode_test.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
Labels: CI:full
