Repository libjxl/libjxl, pull requests merged in 2023-02, with the labels that each got.

#2129 Fix ASAN failure.
  lib/jpegli/bitstream.cc
Labels: CI:full

#2137 fix RoundtripResample2Slow broken by #2122
  lib/jxl/jxl_test.cc
Labels: CI:full

#2142 jpegli encoder: implement jpeg_write_marker API function
  lib/jpegli/encode.cc
  lib/jpegli/encode.h
  lib/jpegli/encode_api_test.cc
  lib/jpegli/encode_internal.h
  lib/jpegli/libjpeg_wrapper.cc
Labels: CI:full

#2159 Fix msan failure.
  lib/jpegli/adaptive_quantization.cc
Labels: CI:full

#2161 Support tables only and abbreviated streams in jpegli encoder.
  lib/jpegli/adaptive_quantization.cc
  lib/jpegli/bitstream.cc
  lib/jpegli/bitstream.h
  lib/jpegli/destination_manager.cc
  lib/jpegli/encode.cc
  lib/jpegli/encode.h
  lib/jpegli/encode_api_test.cc
  lib/jpegli/encode_internal.h
  lib/jpegli/entropy_coding.cc
  lib/jpegli/libjpeg_wrapper.cc
Labels: CI:full

#2179 Fix MSAN failure.
  lib/jpegli/encode_api_test.cc
Labels: CI:full

#2163 not always build all fuzzer targets
  tools/CMakeLists.txt
Labels: CI:full

#2117 Alpha distance
  CHANGELOG.md
  lib/extras/enc/jxl.cc
  lib/extras/enc/jxl.h
  lib/include/jxl/encode.h
  lib/jxl/enc_modular.cc
  lib/jxl/enc_params.h
  lib/jxl/encode.cc
  lib/jxl/jxl_test.cc
  tools/benchmark/benchmark_codec_jxl.cc
  tools/cjxl_main.cc
Labels: enhancement, encoder, api

#2182 update README to have installation info (moving build instructions to a separate file)
  BUILDING.md
  BUILDING_Haiku.md
  BUILDING_OSX.md
  README.md
  plugins/gdk-pixbuf/README.md
  plugins/mime/README.md
Labels: documentation

#2220 remove libbrotlicommon from library requirements
  lib/jxl.cmake
Labels: CI:full
