Repository libjxl/libjxl, pull requests merged in 2023-06, with the labels that each got.

#2517 Rewrite progressive part of jpegli encoder.
  lib/jpegli/bitstream.cc
  lib/jpegli/bitstream.h
  lib/jpegli/encode.cc
  lib/jpegli/encode_api_test.cc
  lib/jpegli/encode_internal.h
  lib/jpegli/entropy_coding-inl.h
  lib/jpegli/entropy_coding.cc
  lib/jpegli/entropy_coding.h
  lib/jpegli/test_utils.h
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
Labels: CI:full

#2518 make e1 lossless also use palette for RGB images
  lib/jxl/enc_fast_lossless.cc
Labels: encoder, density

#2516 fix PixelTestWithICCProfileLossy
  lib/jxl/decode_test.cc
Labels: CI:full

#2525 Simplify Huffman coding data structures, more consistent naming.
  lib/jpegli/bitstream.cc
  lib/jpegli/bitstream.h
  lib/jpegli/encode.cc
  lib/jpegli/encode_api_test.cc
  lib/jpegli/encode_internal.h
  lib/jpegli/entropy_coding-inl.h
  lib/jpegli/entropy_coding.cc
  lib/jpegli/entropy_coding.h
  lib/jpegli/test_utils.cc
  lib/jpegli/test_utils.h
Labels: CI:full

#2537 vardct encoding heuristics improvements
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_group.cc
  lib/jxl/jxl_test.cc
Labels: encoder quality, CI:full

#2522 do more palette
  lib/jxl/enc_modular.cc
Labels: encoder, density

#2540 fix low precision tests
  lib/jxl/decode_test.cc
Labels: testing

#2534 faster jpeg reconstruction
  lib/extras/dec/jxl.cc
  lib/jxl/jpeg/dec_jpeg_data_writer.cc
Labels: djxl, decoder, speedup, CI:full

#2523 improve palette ordering and encode speed
  lib/jxl/enc_modular.cc
  lib/jxl/encode_test.cc
  lib/jxl/modular/transform/enc_palette.cc
Labels: encoder, speedup, density

#2560 allow using cjxl/djxl with stdin/stdout
  tools/djxl_main.cc
  tools/file_io.cc
Labels: cjxl, djxl

#2569 fix --already_downsampled
  lib/extras/enc/jxl.cc
  lib/extras/enc/jxl.h
  tools/cjxl_main.cc
Labels: cjxl, regression

#2570 fix RoundtripLosslessAnimation test
  lib/jxl/jxl_test.cc
Labels: CI:full

#2576 remove Butteraugli from the libjxl API
  CHANGELOG.md
  lib/include/jxl/butteraugli.h
  lib/include/jxl/butteraugli_cxx.h
  lib/jxl/butteraugli_test.cc
  lib/jxl/butteraugli_wrapper.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
Labels: cleanup, api

#2586 improve cjxl help
  tools/cjxl_main.cc
Labels: cjxl

#2587 improve djxl help
  tools/cjxl_main.cc
  tools/djxl_main.cc
Labels: djxl

#2582 Only one file_io
  lib/extras/codec.cc
  lib/extras/dec/color_hints.cc
  lib/extras/enc/pnm.cc
  lib/extras/file_io.h
  lib/jpegli/decode_api_test.cc
  lib/jpegli/input_suspension_test.cc
  lib/jpegli/source_manager_test.cc
  lib/jpegli/test_utils.cc
  lib/jxl/color_management_test.cc
  lib/jxl/decode_test.cc
  lib/jxl/test_utils.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  tools/CMakeLists.txt
  tools/benchmark/benchmark_codec.h
  tools/benchmark/benchmark_codec_custom.cc
  tools/benchmark/benchmark_codec_jpeg.cc
  tools/benchmark/benchmark_file_io.h
  tools/benchmark/benchmark_utils.cc
  tools/benchmark/benchmark_xl.cc
  tools/box/box_list_main.cc
  tools/butteraugli_main.cc
  tools/cjpegli.cc
  tools/cjxl_main.cc
  tools/comparison_viewer/image_loading.cc
  tools/djpegli.cc
  tools/djxl_fuzzer_corpus.cc
  tools/djxl_main.cc
  tools/file_io.cc
  tools/file_io.h
  tools/hdr/exr_to_pq.cc
  tools/hdr/tone_map.cc
  tools/jpegli_dec_fuzzer_corpus.cc
  tools/jxl_from_tree.cc
Labels: CI:full, cleanup

#2590 Add CMake flag PROVISION_DEPENDENCIES
  CMakeLists.txt
Labels: building/portability

#2588 API: remove deprecated things
  CHANGELOG.md
  examples/decode_oneshot.cc
  examples/decode_progressive.cc
  lib/extras/dec/jxl.cc
  lib/include/jxl/decode.h
  lib/include/jxl/encode.h
  lib/include/jxl/types.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/encode.cc
  lib/jxl/fast_dct-inl.h
  lib/jxl/render_pipeline/render_pipeline_test.cc
  lib/jxl/roundtrip_test.cc
  plugins/gdk-pixbuf/pixbufloader-jxl.c
  plugins/gimp/file-jxl-load.cc
  tools/codec_config.h
  tools/decode_basic_info_fuzzer.cc
  tools/djxl_fuzzer.cc
  tools/jni/org/jpeg/jpegxl/wrapper/decoder_jni.cc
  tools/jxlinfo.c
  tools/viewer/load_jxl.cc
Labels: CI:full, cleanup, api

#2589 adjust adaptive quantization for deadzone blocks
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_group.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#2593 organize cjxl/djxl help a bit
  tools/cjxl_main.cc
  tools/cmdline.cc
  tools/cmdline.h
  tools/djxl_main.cc
  tools/speed_stats.cc
Labels: documentation, cjxl, djxl

#2607 Update test expectation.
  lib/jxl/decode_test.cc
Labels: CI:full

#2609 move lib/jxl/enc_butteraugli_pnorm.* to lib/extras/metrics.*
  lib/extras/metrics.cc
  lib/extras/metrics.h
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/modular_test.cc
  lib/jxl/test_utils.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  tools/benchmark/benchmark_xl.cc
  tools/butteraugli_main.cc
  tools/scripts/build_cleaner.py
Labels: cleanup

#2604 Use shared extras codec library for cjxl/djxl if available.
  .github/workflows/conformance.yml
  lib/jxl_extras.cmake
  tools/CMakeLists.txt
Labels: CI:full

#2610 better default modular group size
  lib/jxl/decode_test.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_params.h
  lib/jxl/encode.cc
  tools/cjxl_main.cc
Labels: encoder, density

#2614 conditionally compile debug strings
  lib/jxl/dec_modular.cc
  lib/jxl/frame_header.cc
  lib/jxl/image_metadata.cc
  lib/jxl/modular/modular_image.cc
Labels: cleanup

#2615 conditionally compile low-precision neon-only XYB to RGB code
  lib/jxl/dec_cache.cc
  lib/jxl/render_pipeline/stage_xyb.cc
Labels: cleanup

#2618 remove ClusterGroups()
  lib/jxl/enc_frame.cc
Labels: encoder, cleanup, density

#2613 Refactor jxl_extras.cmake
  lib/extras/enc/jpegli.cc
  lib/extras/enc/jpegli.h
  lib/jxl_extras.cmake
  tools/benchmark/benchmark_codec_jpeg.cc
  tools/cjpegli.cc
Labels: CI:full

#2616 remove dead or deprecated image_ops functions
  lib/extras/tone_mapping_gbench.cc
  lib/jxl/color_management_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_cache.cc
  lib/jxl/enc_detect_dots.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_gaborish.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/enc_image_bundle.cc
  lib/jxl/image.cc
  lib/jxl/image_bundle.h
  lib/jxl/image_ops.h
  lib/jxl/modular/transform/palette.cc
  lib/jxl/opsin_inverse_test.cc
  lib/jxl/splines_test.cc
  tools/benchmark/benchmark_xl.cc
  tools/hdr/local_tone_map.cc
Labels: cleanup

#2621 add --noise to cjxl and make the noise test actually test noise
  lib/jxl/jxl_test.cc
  tools/cjxl_main.cc
Labels: cjxl, testing

#2591 preserve bitdepth when recompressing jxl
  lib/extras/dec/jxl.h
  lib/extras/enc/encode.cc
  lib/include/jxl/types.h
  lib/jxl/decode.cc
  lib/jxl/enc_external_image.cc
  lib/jxl/encode.cc
Labels: cjxl, CI:full, api

#2625 bump up timeout for cross-compile
  .github/workflows/build_test_cross.yml
Labels: meta repo, testing

#2622 improve/simplify bound checking on block_idx
  lib/jxl/jpeg/jpeg_data.cc
Labels: cleanup
