Repository libjxl/libjxl, pull requests merged in 2023-08, with the labels that each got.

#2686 improve metadata handling
  CHANGELOG.md
  lib/extras/dec/color_hints.cc
  lib/extras/dec/color_hints.h
  lib/extras/dec/decode.cc
  lib/extras/dec/jxl.cc
  lib/extras/enc/encode.cc
  lib/extras/enc/encode.h
  lib/extras/enc/jxl.cc
  lib/extras/enc/jxl.h
  lib/include/jxl/encode.h
  lib/jxl/enc_params.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/test_utils.cc
  lib/jxl/test_utils.h
  tools/args.h
  tools/cjxl_main.cc
  tools/djxl_main.cc
Labels: cjxl, djxl, api, container/metadata

#2695 more detailed/useful error messages when jpeg recompression fails
  lib/extras/enc/jxl.cc
Labels: cjxl

#2699 fix overflow in corrupt exif offset
  lib/extras/exif.cc
Labels: djxl, fuzzerbug, CI:full

#2571 add a way to do custom upsampling
  CHANGELOG.md
  lib/extras/enc/jxl.cc
  lib/extras/enc/jxl.h
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
  tools/cjxl_main.cc
Labels: enhancement, encoder, api

#2697 fix cjxl help on --container
  tools/cjxl_main.cc
Labels: documentation, cjxl

#2702 small heuristics tuning for adaptive quant
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_group.cc
  lib/jxl/jxl_test.cc
Labels: encoder quality, CI:full

#2684 Hash-pin workflow Actions, set up dependabot to keep them updated
  .github/dependabot.yml
  .github/workflows/build_test.yml
  .github/workflows/build_test_cross.yml
  .github/workflows/conformance.yml
  .github/workflows/debug_ci.yml
  .github/workflows/fuzz.yml
  .github/workflows/gitlab_mirror.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yaml
  .github/workflows/test_new_highway.yml
Labels: CI:full, meta repo

#2707 remove outdated tables
  doc/tables/adobe.md
  doc/tables/all_tables.pdf
  doc/tables/all_tables.sh
  doc/tables/app0.md
  doc/tables/brn_proto.md
  doc/tables/context_modes.md
  doc/tables/dct_gen.md
  doc/tables/ducky.md
  doc/tables/freq_context.md
  doc/tables/icc.md
  doc/tables/is_zero_base.md
  doc/tables/markdown-pdf.css
  doc/tables/nonzero_buckets.md
  doc/tables/num_nonzero_context.md
  doc/tables/num_nonzeros_base.md
  doc/tables/quant.md
  doc/tables/stock_counts.md
  doc/tables/stock_quant.md
  doc/tables/stock_values.md
  doc/tables/symbol_order.md
Labels: documentation, cleanup

#2709 move standalone fast_lossless from experimental to tools
  tools/fast_lossless/.gitignore
  tools/fast_lossless/README.md
  tools/fast_lossless/build-android.sh
  tools/fast_lossless/build.sh
  tools/fast_lossless/cross_compile_aarch64.sh
  tools/fast_lossless/fast_lossless_main.cc
  tools/fast_lossless/pam-input.h
Labels: meta repo, cleanup

#2700 encoder output streaming
  CHANGELOG.md
  lib/include/jxl/encode.h
  lib/jxl/base/span.h
  lib/jxl/base/status.h
  lib/jxl/decode_test.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/encode_test.cc
  tools/djxl_fuzzer_corpus.cc
Labels: CI:full

#2750 Faster release CI
  .github/workflows/release.yaml
  ci.sh
Labels: highway

#2753 Fix NEON build issue: type marker instance creation
  AUTHORS
  lib/jxl/fast_dct-inl.h
Labels: building/portability, CI:full, highway

#2759 Tune build/test workflow
  .github/workflows/build_test.yml
Labels: CI:full

#2706 improve API documentation structure
  doc/api.txt
  doc/sphinx/api.rst
  doc/sphinx/api_butteraugli.rst
  doc/sphinx/api_color.rst
  doc/sphinx/api_cpp.rst
  doc/sphinx/api_metadata.rst
  lib/include/jxl/cms_interface.h
  lib/include/jxl/codestream_header.h
  lib/include/jxl/color_encoding.h
  lib/include/jxl/decode.h
  lib/include/jxl/decode_cxx.h
  lib/include/jxl/encode_cxx.h
  lib/include/jxl/parallel_runner.h
  lib/include/jxl/resizable_parallel_runner_cxx.h
  lib/include/jxl/thread_parallel_runner_cxx.h
  lib/include/jxl/types.h
Labels: documentation, api
