Repository libjxl/libjxl, pull requests merged in 2023-10, with the labels that each got.

#2836 back-and-forth dcts for ac strategy
  lib/jxl/decode_test.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_ac_strategy.h
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_adaptive_quantization.h
  lib/jxl/enc_cache.h
  lib/jxl/enc_chroma_from_luma.cc
  lib/jxl/enc_group.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/jxl_test.cc
  lib/jxl/passes_test.cc
  tools/optimizer/simplex_fork.py
Labels: encoder, encoder quality, CI:full

#2847 move/remove unused functions
  lib/jxl/enc_debug_image.cc
  lib/jxl/enc_xyb.cc
  lib/jxl/enc_xyb.h
  lib/jxl/image_ops.h
  tools/hdr/local_tone_map.cc
Labels: cleanup

#2845 relax LosslesSmallFewColors test
  lib/jxl/jxl_test.cc
Labels: CI:full

#2865 improve tests (mainly upsampling modes)
  lib/jxl/encode_test.cc
  lib/jxl/roundtrip_test.cc
Labels: encoder, testing

#2868 Make XYB color profile more similar across compilers/targets
  lib/jxl/cms/color_management.cc
  lib/jxl/cms/opsin_params.h
  lib/jxl/color_management_test.cc
  lib/jxl/dec_xyb.cc
Labels: CI:full

#2658 add lossless and e10 to speed tier test
  lib/jxl/speed_tier_test.cc
Labels: CI:full, testing

#2874 allow non-XYB encoding with default colorspace
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
Labels: encoder, api

#2875 fix bug in frame index box writing and add rudimentary test
  lib/jxl/encode.cc
  lib/jxl/roundtrip_test.cc
Labels: bug, encoder, testing

#2855 Finally separate cms from main lib
  lib/extras/enc/jpegli.cc
  lib/extras/hlg.cc
  lib/extras/packed_image_convert.cc
  lib/extras/tone_mapping.cc
  lib/extras/tone_mapping_gbench.cc
  lib/jxl/cms/color_encoding_cms.h
  lib/jxl/cms/color_management.cc
  lib/jxl/cms/color_management.h
  lib/jxl/cms/jxl_cms.cc
  lib/jxl/color_encoding_internal.cc
  lib/jxl/color_encoding_internal.h
  lib/jxl/color_encoding_internal_test.cc
  lib/jxl/color_management_test.cc
  lib/jxl/dec_xyb.cc
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/encode.cc
  lib/jxl/image_metadata.h
  lib/jxl/jpeg/enc_jpeg_data.cc
  lib/jxl/jpeg/enc_jpeg_data.h
  lib/jxl/jxl_test.cc
  lib/jxl/luminance.cc
  lib/jxl/modular_test.cc
  lib/jxl/render_pipeline/stage_from_linear.cc
  lib/jxl/render_pipeline/stage_to_linear.cc
  lib/jxl/render_pipeline/stage_tone_mapping.cc
  lib/jxl/test_utils.cc
  tools/benchmark/benchmark_codec_avif.cc
  tools/comparison_viewer/image_loading.cc
  tools/hdr/display_to_hlg.cc
  tools/hdr/exr_to_pq.cc
  tools/hdr/pq_to_hlg.cc
  tools/hdr/render_hlg.cc
  tools/hdr/tone_map.cc
Labels: CI:full

#2890 simplify ci.sh
  ci.sh
Labels: CI:full

#2884 Link separate libjxl_cms
  .github/workflows/build_test.yml
  .github/workflows/conformance.yml
  examples/CMakeLists.txt
  examples/examples.cmake
  lib/BUILD
  lib/CMakeLists.txt
  lib/extras/codec_test.cc
  lib/extras/packed_image_convert.cc
  lib/include/jxl/types.h
  lib/jxl.cmake
  lib/jxl/cms/color_encoding_cms.h
  lib/jxl/cms/color_management.cc
  lib/jxl/cms/color_management.h
  lib/jxl/cms/jxl_cms.cc
  lib/jxl/cms/jxl_cms.h
  lib/jxl/color_encoding_internal.cc
  lib/jxl/color_encoding_internal.h
  lib/jxl/color_encoding_internal_test.cc
  lib/jxl/dec_xyb.cc
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_debug_image.cc
  lib/jxl/enc_gamma_correct.h
  lib/jxl/encode.cc
  lib/jxl/libjxl_cms.pc.in
  lib/jxl/test_image.cc
  lib/jxl_cms.cmake
  lib/jxl_extras.cmake
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  tools/CMakeLists.txt
  tools/benchmark/benchmark_args.cc
  tools/hdr/exr_to_pq.cc
  tools/scripts/build_cleaner.py
Labels: CI:full

#2915 Make base/ object-free.
  lib/jxl.cmake
  lib/jxl/cache_aligned.cc
  lib/jxl/cache_aligned.h
  lib/jxl/dec_ans.h
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_bit_writer.h
  lib/jxl/enc_icc_codec.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/icc_codec.cc
  lib/jxl/icc_codec.h
  lib/jxl/icc_codec_common.cc
  lib/jxl/image.h
  lib/jxl/modular_test.cc
  lib/jxl/padded_bytes.h
  lib/jxl/padded_bytes_test.cc
  lib/jxl/test_utils.cc
  lib/jxl_cms.cmake
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  tools/CMakeLists.txt
  tools/benchmark/benchmark_xl.cc
  tools/box/CMakeLists.txt
Labels: CI:full

#2916 Drop jxl_cms-static library
  .github/workflows/build_test.yml
  .github/workflows/build_test_md.yml
  examples/CMakeLists.txt
  examples/examples.cmake
  lib/CMakeLists.txt
  lib/jxl.cmake
  lib/jxl/libjxl_cms.pc.in
  lib/jxl_cms.cmake
  lib/jxl_extras.cmake
  third_party/lcms2.cmake
  third_party/skcms.cmake
  tools/CMakeLists.txt
Labels: CI:full
