Repository libjxl/libjxl, pull requests merged in 2023-07, with the labels that each got.

#2627 disable SSSE3 and AVX512 in default builds
  CMakeLists.txt
Labels: question, building/portability

#2620 conditionally compile code for standalone-fjxl
  lib/jxl/enc_fast_lossless.cc
  lib/jxl/enc_fast_lossless.h
Labels: cleanup

#2626 Various cleanups
  lib/extras/codec_test.cc
  lib/jxl/base/compiler_specific.h
  lib/jxl/base/status.h
  lib/jxl/blending.cc
  lib/jxl/butteraugli/butteraugli.cc
  lib/jxl/color_encoding_internal.cc
  lib/jxl/color_management.cc
  lib/jxl/dec_transforms-inl.h
  lib/jxl/dec_xyb-inl.h
  lib/jxl/decode_to_jpeg.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_ans.cc
  lib/jxl/enc_aux_out.cc
  lib/jxl/enc_bit_writer.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_params.h
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/enc_transforms-inl.h
  lib/jxl/fields.cc
  lib/jxl/image_bundle.cc
  lib/jxl/jpeg/jpeg_data.h
  lib/jxl/render_pipeline/low_memory_render_pipeline.cc
  lib/jxl/render_pipeline/stage_blending.cc
  lib/jxl/render_pipeline/stage_epf.cc
  lib/jxl/render_pipeline/stage_from_linear.cc
  lib/jxl/render_pipeline/stage_upsampling.cc
  tools/benchmark/benchmark_codec_jxl.cc
Labels: CI:full, cleanup

#2623 put code for ac strategy debug images behind a compile flag
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_ac_strategy.h
Labels: cleanup

#2611 Factor out the libjpeg-decoding parts of test_utils.cc
  lib/BUILD
  lib/jpegli.cmake
  lib/jpegli/common.h
  lib/jpegli/decode_api_test.cc
  lib/jpegli/encode_api_test.cc
  lib/jpegli/error_handling_test.cc
  lib/jpegli/input_suspension_test.cc
  lib/jpegli/libjpeg_test_util.cc
  lib/jpegli/libjpeg_test_util.h
  lib/jpegli/streaming_test.cc
  lib/jpegli/test_params.h
  lib/jpegli/test_utils-inl.h
  lib/jpegli/test_utils.cc
  lib/jpegli/test_utils.h
  lib/jpegli/types.h
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  tools/scripts/build_cleaner.py
Labels: CI:full

#2634 shard cross compile tests
  .github/workflows/build_test_cross.yml
Labels: CI:full

#2633 fix buffer size in in decode_progressive example
  examples/decode_progressive.cc
Labels: bug, documentation

#2635 jxl-to-jxl conversion: don't use ICC if not needed
  lib/extras/dec/jxl.cc
  lib/extras/dec/jxl.h
  tools/djxl_main.cc
Labels: cjxl

#2644 Move to runtime detection of available codecs in jxl extras.
  lib/CMakeLists.txt
  lib/extras/codec.cc
  lib/extras/codec_test.cc
  lib/extras/dec/apng.cc
  lib/extras/dec/apng.h
  lib/extras/dec/decode.cc
  lib/extras/dec/decode.h
  lib/extras/dec/exr.cc
  lib/extras/dec/exr.h
  lib/extras/dec/gif.cc
  lib/extras/dec/gif.h
  lib/extras/dec/jpg.cc
  lib/extras/dec/jpg.h
  lib/extras/enc/apng.cc
  lib/extras/enc/encode.cc
  lib/extras/enc/exr.cc
  lib/extras/enc/jpg.cc
  lib/extras/jpegli_test.cc
  lib/jpegli.cmake
  lib/jxl/decode_test.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_utils.h
  lib/jxl_extras.cmake
  tools/CMakeLists.txt
  tools/benchmark/benchmark_args.cc
  tools/benchmark/benchmark_codec.cc
  tools/benchmark/benchmark_codec_jpeg.cc
  tools/benchmark/benchmark_codec_jxl.cc
  tools/benchmark/benchmark_codec_png.cc
  tools/benchmark/benchmark_codec_png.h
  tools/benchmark/benchmark_xl.cc
  tools/cjpegli.cc
  tools/cjxl_main.cc
  tools/cmdline.h
  tools/djpegli.cc
  tools/djxl_fuzzer_corpus.cc
  tools/djxl_main.cc
Labels: CI:full

#2648 remove LoadFloat16
  lib/jxl/test_utils.cc
  lib/jxl/test_utils.h
Labels: CI:full

#2637 preparation for distinguishing bad input from bad api usage
  lib/jxl/decode.cc
Labels: decoder, api

#2632 start streaming encoding
  CHANGELOG.md
  lib/include/jxl/encode.h
  lib/jxl/encode.cc
Labels: enhancement, encoder, speedup, api

#2653 tweak lossless e4+
  lib/jxl/enc_modular.cc
  lib/jxl/jxl_test.cc
  lib/jxl/modular/encoding/context_predict.h
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/encoding/enc_ma.cc
  lib/jxl/modular_test.cc
Labels: encoder, speedup, density

#2657 simplify EstimateBits a bit
  lib/jxl/jxl_test.cc
  lib/jxl/modular/encoding/enc_ma.cc
Labels: encoder, speedup

#2665 inline and specialize the symbol reading
  lib/jxl/dec_ans.h
  lib/jxl/dec_context_map.cc
  lib/jxl/dec_group.cc
  lib/jxl/modular/encoding/encoding.cc
Labels: decoder, speedup

#2680 tweak modular decode speed vs binary size
  lib/jxl/dec_ans.h
  lib/jxl/modular/encoding/encoding.cc
Labels: decoder, speedup
