Repository libjxl/libjxl, pull requests merged in 2023-01, with the labels that each got.

#2013 [fast-lossless] More flexible RLE; allow non-16-multiple frame width
  lib/jxl/enc_fast_lossless.cc
Labels: CI:full

#2014 Fix compilation on MSVC
  lib/jxl/enc_fast_lossless.cc
Labels: CI:full

#2010 DZgas' red-green test image correction
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#2023 Make scalar and simd behavior more similar.
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#2021 Build a separate jpegli-static library that libjpeg.so depends on.
  lib/jpegli.cmake
  lib/jpegli/common.cc
  lib/jpegli/common.h
  lib/jpegli/decode.cc
  lib/jpegli/decode.h
  lib/jpegli/decode_api_test.cc
  lib/jpegli/decode_marker.cc
  lib/jpegli/destination_manager.cc
  lib/jpegli/encode.cc
  lib/jpegli/encode.h
  lib/jpegli/encode_api_test.cc
  lib/jpegli/error.cc
  lib/jpegli/libjpeg_wrapper.cc
  lib/jpegli/source_manager.cc
Labels: CI:full

#2024 minor masking adjustment
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#2025 remove TODO about SCALAR
  lib/jxl/jxl_test.cc
Labels: CI:full

#2027 more tolerance
  lib/jxl/jxl_test.cc
Labels: CI:full

#2018 Fix big-endian test for float16
  lib/jxl/modular_test.cc
  lib/jxl/test_utils.h
Labels: CI:full

#2036 Run msan build on ubuntu-20.04.
  .github/workflows/build_test.yml
Labels: CI:full

#2043 Reimplement extras::EncodeJpeg using jpegli-static library.
  lib/extras/codec_test.cc
  lib/extras/enc/jpegli.cc
  lib/extras/enc/jpegli.h
  lib/extras/encode_jpeg.cc
  lib/jpegli.cmake
  lib/jpegli/dct.cc
  lib/jpegli/dct.h
  lib/jpegli/encode.cc
  lib/jpegli/encode.h
  lib/jpegli/encode_api_test.cc
  lib/jpegli/encode_internal.h
  lib/jxl/base/byte_order.h
  lib/jxl/enc_external_image.cc
  lib/jxl/test_utils.h
  lib/jxl_extras.cmake
  tools/benchmark/benchmark_codec_jpeg.cc
  tools/build_cleaner.py
  tools/cjpeg_hdr.cc
Labels: CI:full

#2045 Disable fast-lossless code path for LSB-padded input.
  lib/jxl/encode.cc
Labels: bug

#2058 Fix Lexan build
  lib/jxl/enc_fast_lossless.cc
Labels: merge-0.8

#2069 update README.md and add description of encode effort settings
  README.md
  doc/encode_effort.md
Labels: documentation

#2059 Add jpegli_set_output_format() API function to jpegli decoder.
  lib/extras/dec/decode.cc
  lib/extras/dec/jpegli.cc
  lib/extras/dec/jpg.cc
  lib/extras/dec/jpg.h
  lib/jpegli/common.cc
  lib/jpegli/common.h
  lib/jpegli/decode.cc
  lib/jpegli/decode.h
  lib/jpegli/decode_api_test.cc
  lib/jpegli/decode_internal.h
  lib/jpegli/encode.h
  lib/jpegli/encode_api_test.cc
  lib/jpegli/render.cc
  tools/benchmark/benchmark_codec_jpeg.cc
  tools/cjxl_main.cc
Labels: CI:full

#2060 Add a separate extras/jpegli_test.cc for the jpegli API in extras.
  lib/extras/codec_test.cc
  lib/extras/jpegli_test.cc
  lib/jxl_tests.cmake
Labels: CI:full

#2062 Use apt-spy2 to select closest mirror.
  .github/workflows/build_test.yml
  .github/workflows/conformance.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yaml
Labels: CI:full

#2120 fix palette bug
  lib/jxl/enc_fast_lossless.cc
Labels: merge-0.8
