Repository libjxl/libjxl, pull requests merged in 2023-09, with the labels that each got.

#2767 better handling of PNG with sBIT chunk
  lib/extras/dec/apng.cc
Labels: cjxl

#2763 Split cross-build/test into phases
  .github/workflows/build_test_cross.yml
  CMakeLists.txt
  tools/scripts/test_cost-arm64-lowprecision.zip
  tools/scripts/test_cost-arm64.zip
  tools/scripts/test_cost-armhf.zip
  tools/scripts/test_cost-i386.zip
Labels: CI:full

#2777 Faster debug tests.
  .github/workflows/build_test.yml
  CMakeLists.txt
Labels: CI:full

#2798 relax distance check
  lib/jxl/butteraugli/butteraugli_test.cc
Labels: CI:full

#2803 use link to nicer view for security score card
  README.md
Labels: meta repo

#2802 Faster MSAN build
  .github/workflows/build_test.yml
  ci.sh
Labels: CI:full

#2806 add badge for OpenSSF best practices
  README.md
Labels: meta repo

#2810 add PAT for branch protection check
  .github/workflows/scorecard.yml
Labels: meta repo

#2819 Untie cms/ some icc utilities from PaddedBytes
  lib/extras/codec_test.cc
  lib/extras/enc/jpegli.cc
  lib/extras/packed_image_convert.cc
  lib/jxl/base/span.h
  lib/jxl/color_encoding_internal.cc
  lib/jxl/color_encoding_internal.h
  lib/jxl/color_management.cc
  lib/jxl/color_management.h
  lib/jxl/color_management_test.cc
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_icc_codec.cc
  lib/jxl/enc_icc_codec.h
  lib/jxl/encode.cc
  lib/jxl/icc_codec_test.cc
  lib/jxl/jpeg/enc_jpeg_data.cc
  lib/jxl/jpeg/jpeg_data.cc
  lib/jxl/jpeg/jpeg_data.h
  lib/jxl/jxl_cms.cc
  lib/jxl/render_pipeline/render_pipeline_test.cc
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_image.cc
  tools/benchmark/benchmark_codec_avif.cc
  tools/comparison_viewer/image_loading.cc
Labels: CI:full

#2828 Add jxl::cms::ColorEncoding
  lib/extras/codec_test.cc
  lib/extras/dec/color_description_test.cc
  lib/extras/enc/jpegli.cc
  lib/extras/hlg.cc
  lib/extras/jpegli_test.cc
  lib/extras/packed_image_convert.cc
  lib/extras/tone_mapping.cc
  lib/extras/tone_mapping_gbench.cc
  lib/jxl/color_encoding_external.h
  lib/jxl/color_encoding_internal.cc
  lib/jxl/color_encoding_internal.h
  lib/jxl/color_encoding_internal_test.cc
  lib/jxl/color_management.cc
  lib/jxl/color_management_test.cc
  lib/jxl/dec_xyb.cc
  lib/jxl/decode.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_debug_image.cc
  lib/jxl/encode.cc
  lib/jxl/image_bundle.h
  lib/jxl/jxl_cms.cc
  lib/jxl/test_image.cc
  lib/jxl/test_utils.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  tools/benchmark/benchmark_args.cc
  tools/benchmark/benchmark_codec_avif.cc
  tools/benchmark/benchmark_codec_custom.cc
  tools/hdr/display_to_hlg.cc
  tools/hdr/exr_to_pq.cc
  tools/hdr/pq_to_hlg.cc
Labels: CI:full

#2825 fix e8+ VarDCT with noise enabled
  lib/jxl/dec_cache.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.cc
  lib/jxl/enc_adaptive_quantization.cc
Labels: bug, encoder
