Repository libjxl/libjxl, pull requests merged in 2023-12, with the labels that each got.

#2998 Refactor EncodeFrame function to prepare it for streaming.
  lib/include/jxl/encode.h
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_adaptive_quantization.h
  lib/jxl/enc_butteraugli_comparator.cc
  lib/jxl/enc_butteraugli_comparator.h
  lib/jxl/enc_cache.cc
  lib/jxl/enc_cache.h
  lib/jxl/enc_chroma_from_luma.cc
  lib/jxl/enc_chroma_from_luma.h
  lib/jxl/enc_coeff_order.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/enc_heuristics.h
  lib/jxl/enc_image_bundle.cc
  lib/jxl/enc_image_bundle.h
  lib/jxl/enc_modular.cc
  lib/jxl/enc_modular.h
  lib/jxl/enc_params.h
  lib/jxl/enc_quant_weights.cc
  lib/jxl/enc_quant_weights.h
  lib/jxl/enc_toc.cc
  lib/jxl/enc_toc.h
  lib/jxl/enc_xyb.cc
  lib/jxl/enc_xyb.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
  lib/jxl/frame_dimensions.h
  lib/jxl/jxl_test.cc
  lib/jxl/modular_test.cc
  lib/jxl/passes_state.h
  lib/jxl/test_utils.cc
  lib/jxl/test_utils.h
  lib/jxl/toc_test.cc
  tools/jxl_from_tree.cc
Labels: CI:full

#3003 Fix dead-end in jpeg-transcode flow
  lib/jxl/decode.cc
  tools/djxl_fuzzer.cc
Labels: CI:full

#2987 Streamline the build
  .github/workflows/build_test.yml
  .github/workflows/build_test_cross.yml
  .github/workflows/conformance.yml
  .github/workflows/release.yaml
  CMakeLists.txt
  debian/libjxl-dev.install
  deps.sh
  examples/CMakeLists.txt
  lib/CMakeLists.txt
  lib/compatibility.cmake
  lib/jpegli.cmake
  lib/jxl.cmake
  lib/jxl/enc_bit_writer.cc
  lib/jxl/jxl_test.cc
  lib/jxl/libjxl_cms.pc.in
  lib/jxl_benchmark.cmake
  lib/jxl_cms.cmake
  lib/jxl_extras.cmake
  lib/jxl_tests.cmake
  lib/jxl_threads.cmake
  third_party/CMakeLists.txt
  third_party/lcms2.cmake
  third_party/skcms.cmake
  third_party/testing.cmake
  tools/CMakeLists.txt
  tools/benchmark/benchmark_codec.cc
  tools/comparison_viewer/CMakeLists.txt
  tools/scripts/ossfuzz-build.sh
  tools/wasm_demo/CMakeLists.txt
Labels: CI:full, merge-0.9

#3017 Implement streaming encoder mode with constant memory usage.
  lib/jxl/ans_test.cc
  lib/jxl/dec_ans.cc
  lib/jxl/enc_ans.cc
  lib/jxl/enc_ans.h
  lib/jxl/enc_ans_params.h
  lib/jxl/enc_bit_writer.cc
  lib/jxl/enc_bit_writer.h
  lib/jxl/enc_cache.cc
  lib/jxl/enc_cache.h
  lib/jxl/enc_cluster.cc
  lib/jxl/enc_cluster.h
  lib/jxl/enc_coeff_order.cc
  lib/jxl/enc_coeff_order.h
  lib/jxl/enc_context_map.cc
  lib/jxl/enc_entropy_coder.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_group.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/enc_heuristics.h
  lib/jxl/enc_icc_codec.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_modular.h
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/enc_splines.cc
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/passes_state.h
Labels: CI:full

#3046 fix RoundtripAnimationPatches
  lib/jxl/jxl_test.cc
Labels: CI:full

#3047 Cut dependency decoder -> *cms
  lib/jxl.cmake
  lib/jxl/cms/color_encoding_cms.h
  lib/jxl/cms/color_management.h
  lib/jxl/cms/jxl_cms.cc
  lib/jxl/cms/jxl_cms.h
  lib/jxl/cms/jxl_cms_internal.h
  lib/jxl/color_encoding_internal.cc
  lib/jxl/color_encoding_internal.h
  lib/jxl/dec_xyb.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  tools/hdr/exr_to_pq.cc
Labels: CI:full

#3053 Move JxlGetDefaultCms to public API
  lib/extras/dec/jxl.cc
  lib/extras/enc/jpegli.cc
  lib/extras/hlg.cc
  lib/extras/packed_image_convert.cc
  lib/extras/tone_mapping.cc
  lib/include/jxl/cms.h
  lib/jxl/cms/color_encoding_cms.h
  lib/jxl/cms/jxl_cms.cc
  lib/jxl/color_encoding_internal.h
  lib/jxl/color_management_test.cc
  lib/jxl/decode_test.cc
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
  lib/jxl/fast_math_test.cc
  lib/jxl/gradient_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/modular_test.cc
  lib/jxl/opsin_image_test.cc
  lib/jxl/opsin_inverse_test.cc
  lib/jxl/passes_test.cc
  lib/jxl/patch_dictionary_test.cc
  lib/jxl/preview_test.cc
  lib/jxl/render_pipeline/render_pipeline_test.cc
  lib/jxl/roundtrip_test.cc
  lib/jxl/speed_tier_test.cc
  lib/jxl/splines_test.cc
  lib/jxl/test_utils.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  tools/benchmark/benchmark_codec_avif.cc
  tools/benchmark/benchmark_codec_webp.cc
  tools/benchmark/benchmark_xl.cc
  tools/butteraugli_main.cc
  tools/comparison_viewer/image_loading.cc
  tools/djxl_fuzzer_corpus.cc
  tools/hdr/image_utils.h
  tools/hdr/local_tone_map.cc
  tools/jxl_from_tree.cc
  tools/ssimulacra2.cc
  tools/ssimulacra_main.cc
  tools/xyb_range.cc
Labels: CI:full, api

#3061 Fix pkgconfig for linking to an installed static library.
  flake.nix
  lib/jxl.cmake
  lib/jxl/libjxl.pc.in
  lib/jxl/libjxl_cms.pc.in
  lib/jxl_cms.cmake
  lib/jxl_threads.cmake
  lib/threads/libjxl_threads.pc.in
Labels: CI:full, merge-0.9

#3071 Fix deps.sh
  deps.sh
Labels: merge-0.9

#3079 fix release contens permissions
  .github/workflows/release.yaml
Labels: merge-0.9

#3080 bump vcpkg version
  .github/workflows/release.yaml
Labels: merge-0.9

#3073 Revive JPEGXL_STATIC
  .github/workflows/release.yaml
  CMakeLists.txt
  lib/jxl_benchmark.cmake
Labels: CI:full, merge-0.9

#3083 When building with skcms, incorporate it into libjxl_cms
  lib/jxl/cms/jxl_cms.cc
  lib/jxl_cms.cmake
  third_party/skcms.cmake
Labels: CI:full, merge-0.9

#3085 Set ENABLE_JPEGLI conditioned on the existence of the libjpeg-turbo submodule
  CMakeLists.txt
Labels: merge-0.9
