Repository libjxl/libjxl, pull requests merged in 2023-04, with the labels that each got.

#2354 Support cinfo reuse in jpegli encoder and decoder.
  lib/extras/enc/jpegli.cc
  lib/jpegli/bitstream.cc
  lib/jpegli/decode.cc
  lib/jpegli/decode_api_test.cc
  lib/jpegli/decode_internal.h
  lib/jpegli/destination_manager.cc
  lib/jpegli/encode.cc
  lib/jpegli/encode.h
  lib/jpegli/encode_api_test.cc
  lib/jpegli/encode_internal.h
  lib/jpegli/quant.cc
  lib/jpegli/quant.h
  lib/jpegli/source_manager.cc
  lib/jpegli/test_utils.cc
  lib/jpegli/test_utils.h
Labels: CI:full

#2355 quantization improvement
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_group.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  tools/optimizer/simplex_fork.py
Labels: CI:full

#2356 Support partial input files in jpegli decoder.
  lib/jpegli/decode.cc
  lib/jpegli/decode_api_test.cc
  lib/jpegli/decode_scan.cc
  lib/jpegli/source_manager_test.cc
  lib/jpegli/test_utils.cc
  lib/jpegli/test_utils.h
Labels: CI:full

#2357 Move all source manager operations to ConsumeInput()
  lib/jpegli/decode.cc
  lib/jpegli/decode_api_test.cc
  lib/jpegli/decode_internal.h
  lib/jpegli/decode_marker.cc
  lib/jpegli/decode_marker.h
  lib/jpegli/decode_scan.cc
  lib/jpegli/decode_scan.h
  lib/jpegli/source_manager.cc
  lib/jpegli/source_manager.h
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
Labels: CI:full

#2378 Support input smoothing in jpegli encoder.
  lib/jpegli/downsample.cc
  lib/jpegli/downsample.h
  lib/jpegli/encode.cc
  lib/jpegli/encode_api_test.cc
  lib/jpegli/encode_internal.h
  lib/jpegli/test_utils.cc
  lib/jpegli/test_utils.h
Labels: CI:full

#2397 small vardct quality improvement (0.1 %)
  lib/jxl/decode_test.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#2401 remove constructor for HuffmanTableEntry
  lib/jpegli/decode.cc
  lib/jpegli/huffman.h
Labels: CI:full

#2405 Fix msan and i686 builds.
  lib/jpegli/bitstream.cc
  lib/jpegli/encode_api_test.cc
Labels: CI:full

#2407 jpegli: smoothing
  lib/jpegli/decode.cc
  lib/jpegli/decode_api_test.cc
  lib/jpegli/decode_internal.h
  lib/jpegli/decode_marker.cc
  lib/jpegli/input_suspension_test.cc
  lib/jpegli/render.cc
  lib/jpegli/streaming_test.cc
  lib/jpegli/test_utils.cc
Labels: CI:full

#2422 Adjust HfModulation in initial adaptive quant
  lib/jxl/decode_test.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/jxl_test.cc
  tools/optimizer/simplex_fork.py
Labels: CI:full

#2426 trigger spline limits earlier
  lib/jxl/splines.cc
  lib/jxl/splines.h
  lib/jxl/splines_test.cc
Labels: CI:full

#2424 Improve Adaptive Quantization after AC Strategy
  lib/jxl/decode_test.cc
  lib/jxl/enc_group.cc
  lib/jxl/jxl_test.cc
Labels: encoder quality, CI:full

#2435 Fix msan and cross-compile builds.
  lib/jpegli/test_utils.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#2425 take color into account in estimated area of splines
  lib/jxl/splines.cc
Labels: spec

#2418 fix alpha clamping in kMulAdd blending
  lib/jxl/alpha.cc
Labels: bug, decoder
