Repository libjxl/libjxl, pull requests merged in 2024-06, with the labels that each got.

#3619 Typos exterminatus
  .github/workflows/pull_request.yml
  .github/workflows/test_new_highway.yml
  ci.sh
  doc/fuzzing.md
  lib/extras/dec/apng.cc
  lib/extras/dec/gif.cc
  lib/extras/enc/apng.cc
  lib/extras/time.cc
  lib/jpegli/adaptive_quantization.cc
  lib/jpegli/dct-inl.h
  lib/jpegli/decode_internal.h
  lib/jpegli/downsample.cc
  lib/jpegli/encode.cc
  lib/jpegli/encode_finish.cc
  lib/jpegli/encode_streaming.cc
  lib/jpegli/entropy_coding.cc
  lib/jpegli/error.cc
  lib/jpegli/error_handling_test.cc
  lib/jpegli/idct.cc
  lib/jpegli/render.cc
  lib/jpegli/streaming_test.cc
  lib/jpegli/test_utils-inl.h
  lib/jpegli/test_utils.cc
  lib/jxl/butteraugli/butteraugli_test.cc
  lib/jxl/cms/jxl_cms_internal.h
  lib/jxl/coeff_order.h
  lib/jxl/convolve-inl.h
  lib/jxl/dct-inl.h
  lib/jxl/decode_test.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_fast_lossless.cc
  lib/jxl/enc_group.cc
  lib/jxl/image_metadata.cc
  lib/jxl/modular/encoding/enc_ma.cc
  lib/jxl/modular/transform/squeeze.cc
  lib/jxl/render_pipeline/simple_render_pipeline.cc
  lib/jxl/render_pipeline/test_render_pipeline_stages.h
  lib/jxl/roundtrip_test.cc
  lib/jxl/test_utils.cc
  plugins/gimp/file-jxl-load.cc
  tools/butteraugli_main.cc
  tools/conformance/lcms2.py
  tools/optimizer/apply_simplex.py
  tools/scripts/typos.toml
  tools/wasm_demo/manual_decode_demo.html
Labels: CI:full

#3620 fix issues in pam encode/decode
  lib/extras/dec/pnm.cc
  lib/extras/enc/pnm.cc
Labels: bug

#3563 Reduce generation loss
  lib/jxl/enc_frame.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/enc_modular.cc
  lib/jxl/jxl_test.cc
  lib/jxl/passes_test.cc
Labels: encoder

#3622 improve lossless e2/e3 for > 10-bit images and make -E 1 do something when doing -e 2
  lib/jxl/enc_modular.cc
  lib/jxl/encode.cc
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl/modular/encoding/enc_encoding.h
  lib/jxl/modular/encoding/encoding.cc
  lib/jxl/modular/encoding/encoding.h
Labels: encoder

#3648 Allow to ask for memory with 0-side padding.
  lib/jxl/image.cc
  lib/jxl/image.h
  lib/jxl/memory_manager_internal.cc
  lib/jxl/memory_manager_internal.h
  lib/jxl/render_pipeline/low_memory_render_pipeline.cc
Labels: CI:full

#3661 fix broken check for fast lossless conditions
  lib/jxl/encode.cc
Labels: bug, encoder

#3662 fix bug in huffman-rle-gradient (e1) specialized decode path
  lib/jxl/modular/encoding/encoding.cc
Labels: bug, decoder, regression
