Repository libjxl/libjxl, pull requests merged in 2024-04, with the labels that each got.

#3450 Prevent integer overflow
  lib/jxl/modular/transform/enc_palette.cc
Labels: CI:full

#3469 Move jpeglib include workaround to separate header
  examples/decode_progressive.cc
  lib/extras/dec/jpg.cc
  lib/extras/dec/jxl.cc
  lib/extras/enc/jpg.cc
  lib/jpegli/common.h
  lib/jpegli/libjpeg_test_util.cc
  lib/jpegli/test_utils.h
  lib/jxl/base/compiler_specific.h
  lib/jxl/base/exif.h
  lib/jxl/base/include_jpeglib.h
  lib/jxl/base/matrix_ops.h
  lib/jxl/convolve_test.cc
  lib/jxl/dct_for_test.h
  lib/jxl/dec_transforms-inl.h
  lib/jxl/dec_transforms_testonly.cc
  lib/jxl/dec_transforms_testonly.h
  lib/jxl/enc_fields.cc
  lib/jxl/fake_parallel_runner_testonly.h
  lib/jxl/fields.cc
  lib/jxl/image.h
  lib/jxl/image_test_utils.h
  lib/jxl/modular/encoding/enc_debug_tree.cc
  lib/jxl/modular/transform/transform.cc
  lib/jxl/render_pipeline/test_render_pipeline_stages.h
  lib/jxl/sanitizers.h
  lib/jxl/splines.cc
  lib/jxl/test_image.cc
  lib/jxl/test_image.h
  lib/jxl/test_utils.h
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  lib/lib.gni
  tools/decode_basic_info_fuzzer.cc
  tools/jxlinfo.c
Labels: merge-0.10

#3477 fix tsan error in ModularFrameEncoder
  lib/jxl/enc_modular.cc
Labels: CI:full

#3479 add tsan to ci
  .github/workflows/build_test.yml
Labels: CI:full

#3329 Round towards zero, not upwards
  .github/workflows/conformance.yml
  lib/jxl/cms/jxl_cms_internal.h
  lib/jxl/color_management_test.cc
Labels: CI:full

#3506 de-duplicate list of supported input/output codecs for tool help screens
  lib/extras/dec/decode.cc
  lib/extras/dec/decode.h
  lib/extras/enc/encode.cc
  lib/extras/enc/encode.h
  tools/cjpegli.cc
  tools/cjxl_main.cc
  tools/djpegli.cc
  tools/djxl_main.cc
Labels: cjxl, djxl, jpegli

#3423 Unbreak static link on windows
  CMakeLists.txt
Labels: CI:full

#3520 Increase quality in chromacity planes.
  lib/jxl/decode_test.cc
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_frame.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/passes_test.cc
  lib/jxl/render_pipeline/render_pipeline_test.cc
  lib/jxl/roundtrip_test.cc
Labels: CI:full

#935 Removed warnings under Visual Studio (Windows)
  AUTHORS
  lib/jxl/ac_context.h
Labels: building/portability, unrelated to 1.0

#3529 New AR control field heuristics.
  .github/workflows/conformance.yml
  lib/jxl/dec_cache.cc
  lib/jxl/dec_cache.h
  lib/jxl/dec_frame.cc
  lib/jxl/dec_group.cc
  lib/jxl/dec_group.h
  lib/jxl/enc_adaptive_quantization.cc
  lib/jxl/enc_ar_control_field.cc
  lib/jxl/enc_ar_control_field.h
  lib/jxl/enc_cache.cc
  lib/jxl/enc_cache.h
  lib/jxl/enc_frame.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/enc_heuristics.h
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/modular/encoding/enc_encoding.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  lib/lib.gni
Labels: CI:full

#3537 fix RoundtripLargeEmptyModular
  lib/jxl/enc_frame.cc
Labels: CI:full
