Repository libjxl/libjxl, pull requests merged in 2024-03, with the labels that each got.

#3351 Use std::array based Vector3 and Matrix3x3 in matrix-ops
  lib/extras/tone_mapping.cc
  lib/jxl/base/matrix_ops.h
  lib/jxl/cms/jxl_cms.cc
  lib/jxl/cms/jxl_cms_internal.h
  lib/jxl/cms/opsin_params.h
  lib/jxl/cms/tone_mapping-inl.h
  lib/jxl/cms/tone_mapping.h
  lib/jxl/cms/tone_mapping_test.cc
  lib/jxl/dec_xyb.cc
  lib/jxl/dec_xyb.h
  lib/jxl/enc_xyb.cc
  lib/jxl/image_metadata.cc
  lib/jxl/image_metadata.h
  lib/jxl/opsin_image_test.cc
  lib/jxl/opsin_params.cc
  lib/jxl/opsin_params.h
  lib/jxl/render_pipeline/stage_from_linear.cc
  lib/jxl/render_pipeline/stage_to_linear.cc
  tools/gauss_blur.cc
  tools/hdr/exr_to_pq.cc
Labels: CI:full

#3359 fix bug in lossless e1 palette writing
  lib/jxl/enc_fast_lossless.cc
Labels: bug, encoder, merge-0.10

#3361 Fix streaming mode for images where last the DC group is small.
  lib/jxl/enc_frame.cc
  lib/jxl/jxl_test.cc
Labels: merge-0.10

#3375 Revert "disable installion of MIME file (#2259)"
  debian/libjxl-gdk-pixbuf.install
  plugins/CMakeLists.txt
  plugins/mime/CMakeLists.txt
Labels: CI:full, merge-0.10

#3379 Fix assert in CMS stage
  lib/extras/enc/jpegli.cc
  lib/jxl/color_encoding_internal.h
  lib/jxl/color_management_test.cc
  lib/jxl/enc_image_bundle.cc
  lib/jxl/enc_xyb.cc
  lib/jxl/render_pipeline/stage_cms.cc
Labels: merge-0.10

#3385 preserve bitdepth when taking jxl input
  lib/extras/dec/decode.cc
Labels: cjxl, merge-0.10

#3391 Simplify test case for prefix coding bug.
  lib/jxl/jxl_test.cc
Labels: CI:full

#3405 Drop toxic gmock dependency
  .github/workflows/release.yaml
  CMakeLists.txt
  bash_test.sh
  ci.sh
  debian/control
  doc/developing_in_debian.md
  doc/developing_in_windows_vcpkg.md
  flake.nix
  lib/extras/codec_test.cc
  lib/extras/jpegli_test.cc
  lib/jpegli.cmake
  lib/jpegli/testing.h
  lib/jxl/alpha_test.cc
  lib/jxl/base/common.h
  lib/jxl/blending_test.cc
  lib/jxl/cms/color_encoding_cms.h
  lib/jxl/cms/tone_mapping.h
  lib/jxl/color_management_test.cc
  lib/jxl/decode_test.cc
  lib/jxl/enc_photon_noise_test.cc
  lib/jxl/jxl_test.cc
  lib/jxl/modular_test.cc
  lib/jxl/noise.h
  lib/jxl/passes_test.cc
  lib/jxl/render_pipeline/render_pipeline_test.cc
  lib/jxl/render_pipeline/stage_noise.cc
  lib/jxl/splines.cc
  lib/jxl/splines.h
  lib/jxl/splines_gbench.cc
  lib/jxl/splines_test.cc
  lib/jxl/testing.h
  lib/jxl_tests.cmake
  tools/scripts/fix_headers.sh
Labels: CI:full

#3397 include local jxl headers before system headers
  lib/jxl.cmake
  lib/jxl_cms.cmake
  lib/jxl_extras.cmake
Labels: building/portability, CI:full

#3419 extra channels for decoding to png
  lib/extras/enc/apng.cc
  tools/djxl_main.cc
Labels: CI:full

#3420 tweak palette heuristics
  lib/jxl/enc_modular.cc
  lib/jxl/enc_modular.h
  lib/jxl/encode_test.cc
  lib/jxl/modular/transform/enc_palette.cc
  lib/jxl/modular/transform/palette.h
  lib/jxl/modular_test.cc
Labels: encoder, density
