Repository libjxl/libjxl, pull requests merged in 2024-02, with the labels that each got.

#3227 Encode lossless Modular extra channels in streaming mode.
  lib/jxl/dec_frame.cc
  lib/jxl/dec_modular.cc
  lib/jxl/enc_frame.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_modular.h
  lib/jxl/jxl_test.cc
Labels: CI:full

#3228 Enable streaming mode for modular mode.
  lib/jxl/enc_frame.cc
  lib/jxl/enc_modular.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#3229 Enable streaming encoding for different modular group sizes.
  lib/jxl/enc_frame.cc
  lib/jxl/jxl_test.cc
Labels: CI:full

#3238 Move loosely related code from image.cc
  lib/jxl/gradient_test.cc
  lib/jxl/image.cc
  lib/jxl/image.h
  lib/jxl/image_ops.cc
  lib/jxl/image_ops.h
  lib/jxl/image_ops_test.cc
  lib/jxl/simd_util.cc
  lib/jxl/simd_util.h
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  lib/lib.gni
  tools/gauss_blur_test.cc
Labels: CI:full

#3241 Try ubuntu-22.04 for MSAN again
  .github/workflows/build_test.yml
  .github/workflows/build_test_cross.yml
  .github/workflows/debug_ci.yml
Labels: CI:full

#3269 have default buffering mode as in cjxl
  lib/include/jxl/encode.h
  lib/jxl/enc_frame.cc
  lib/jxl/enc_params.h
  lib/jxl/encode.cc
  lib/jxl/encode_test.cc
  lib/jxl/jxl_test.cc
  tools/cjxl_main.cc
  tools/streaming_fuzzer.cc
Labels: encoder

#3274 Fix the usage of fixed trees with streaming mode.
  lib/jxl/jxl_test.cc
  lib/jxl/modular/encoding/enc_encoding.cc
Labels: CI:full

#3288 Avoid doing complex quantization at effort 3.
  lib/jxl/enc_group.cc
  lib/jxl/jxl_test.cc
  lib/jxl/speed_tier_test.cc
Labels: CI:full

#3331 Fix streaming encoding with more than 255 DC groups.
  lib/jxl/enc_cache.h
  lib/jxl/enc_frame.cc
Labels: merge-0.10

#3332 Cap the number of reference properties to the # of extra channels.
  lib/jxl/enc_modular.cc
Labels: merge-0.10

#3337 Do not use Variable predictor by default at e9.
  lib/jxl/enc_modular.cc
Labels: merge-0.10

#3344 Non-no-op clang-tidy fixes
  lib/jxl/fast_dct.cc
  lib/jxl/fast_dct.h
  lib/jxl/fast_dct_test.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  lib/lib.gni
  tools/benchmark/benchmark_codec_webp.cc
Labels: CI:full
