Repository libjxl/libjxl, pull requests merged in 2024-09, with the labels that each got.

#3797 exclude test_jpegli_jni_wrapper
  .github/workflows/build_test_cross.yml
Labels: CI:full

#3796 fix tests from #3786
  lib/jxl/jxl_test.cc
Labels: CI:full

#3802 disable test_jpegli_jni_wrapper in converage test
  .github/workflows/build_test.yml
Labels: CI:full

#3811 Fix build with old gcc
  lib/jxl/convolve-inl.h
Labels: CI:full

#3815 update date in changelog
  CHANGELOG.md
Labels: CI:full

#3831 binary releases for Ubuntu 24.04
  .github/workflows/release.yaml
Labels: CI:full, merge-0.11

#3828 loop_filter.{c,h}: Use correct header for std::abs
  lib/jxl/loop_filter.h
Labels: merge-0.11

#3825 fix cmake script for homebrew a2x
  CMakeLists.txt
Labels: building/portability, merge-0.11

#3821 Fix jpg.cc for MinGW-w64
  lib/extras/enc/jpg.cc
Labels: merge-0.11

#3835 Don't abort in the destructor of allotment if allocation failed
  lib/jxl/enc_bit_writer.cc
  tools/streaming_fuzzer.cc
Labels: CI:full, merge-0.11

#3845 Return if resizing fails
  lib/jxl/encode.cc
Labels: CI:full, merge-0.11

#3837 Don’t set CMAKE_MSVC_RUNTIME_LIBRARY in debug builds
  CMakeLists.txt
Labels: merge-0.11
