Repository libjxl/libjxl, pull requests merged in 2024-05, with the labels that each got.

#3566 fix arithmetic issue in dot detection
  lib/jxl/enc_linalg.cc
  lib/jxl/enc_linalg_test.cc
Labels: bug, encoder

#3547 add option for generation loss testing in benchmark_xl
  tools/benchmark/benchmark_args.cc
  tools/benchmark/benchmark_args.h
  tools/benchmark/benchmark_xl.cc
Labels: testing

#3536 minor optimization for enc_heuristics
  lib/jxl/enc_heuristics.cc
Labels: encoder, encoder quality, CI:full

#3582 Actually use JxlMemoryManager
  lib/extras/dec/jxl.cc
  lib/extras/dec/jxl.h
  lib/extras/enc/jxl.cc
  lib/extras/enc/jxl.h
  lib/jxl/cache_aligned.cc
  lib/jxl/cache_aligned.h
  lib/jxl/chroma_from_luma.cc
  lib/jxl/chroma_from_luma.h
  lib/jxl/dec_ans.cc
  lib/jxl/dec_ans.h
  lib/jxl/dec_cache.cc
  lib/jxl/dec_frame.cc
  lib/jxl/dec_group.cc
  lib/jxl/dec_modular.cc
  lib/jxl/enc_ac_strategy.cc
  lib/jxl/enc_chroma_from_luma.cc
  lib/jxl/enc_chroma_from_luma.h
  lib/jxl/enc_dot_dictionary.cc
  lib/jxl/enc_dot_dictionary.h
  lib/jxl/enc_frame.cc
  lib/jxl/enc_group.cc
  lib/jxl/enc_heuristics.cc
  lib/jxl/enc_modular.cc
  lib/jxl/enc_patch_dictionary.cc
  lib/jxl/encode.cc
  lib/jxl/encode_internal.h
  lib/jxl/fields_test.cc
  lib/jxl/image.cc
  lib/jxl/image.h
  lib/jxl/image_ops_test.cc
  lib/jxl/memory_manager_internal.cc
  lib/jxl/memory_manager_internal.h
  lib/jxl/padded_bytes.h
  lib/jxl/render_pipeline/render_pipeline_test.cc
  lib/jxl/render_pipeline/stage_noise.cc
  lib/jxl/render_pipeline/stage_noise.h
  lib/jxl/render_pipeline/stage_write.cc
  lib/jxl/simd_util.cc
  lib/jxl/simd_util.h
  lib/jxl/splines.cc
  lib/jxl/splines.h
  lib/jxl/splines_gbench.cc
  lib/jxl/splines_test.cc
  lib/jxl_lists.bzl
  lib/jxl_lists.cmake
  lib/lib.gni
  tools/benchmark/benchmark_codec.cc
  tools/benchmark/benchmark_codec.h
  tools/benchmark/benchmark_codec_jxl.cc
  tools/benchmark/benchmark_codec_jxl.h
  tools/benchmark/benchmark_xl.cc
  tools/jxl_from_tree.cc
Labels: CI:full

#3610 More jpeglib unpoisoning
  lib/jpegli/libjpeg_test_util.cc
Labels: CI:full
